### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#10]
Everyone's favorite topic!

I was just poking through the code, and noticed what seem to be some ambiguity in licensing, comparing the top-level license to other bits of the code which seem to be GPL (eg, in parsers/*.py).

Maybe it's worth thinking about picking a single license to use across the board?

GPL is probably not a great idea here, given that it's a library that could be embedded in all kinds of things.  I would recommend a BSD-style license, having just gone through all this for librosa.  See also: http://choosealicense.com/ .

Maybe put it to a vote?  Just opening up the discussion here.

**Comment by bmcfee** [comment]
So.. is everyone cool with BSD2/ISC?

**Comment by justinsalamon** [comment]
:+1:
