### ISSUE TITLE
Unit test error for schema_test.py

### ISSUE THREAD

**Issue by justinsalamon** [marl/jams#103]
I just pulled the latest&greatest and ran the unit tests (from the tests folder) before getting started on my transcription wrapper, but one test is failing and I'm not entirely clear on what's going on:

```bash
ERROR: Failure: KeyError ('jams/tests/fixtures/schema')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/Users/justin/Documents/dev/jams/jams/tests/schema_test.py", line 64, in test_schema_local
    'schema'))
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 954, in resource_filename
    self, resource_name
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1652, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1673, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'jams/tests/fixtures/schema'

----------------------------------------------------------------------
```
@bmcfee Any chance you can help a brother out?

**Comment by bmcfee** [comment]
This is an artifact of nesting the `tests/` directory under the package rather than at the top-level.

Does it work if you run it from the top level dir in the repo as:
```bash
$ nosetests -w jams/tests
```

**Comment by justinsalamon** [comment]
afraid not, still getting same error.

**Comment by justinsalamon** [comment]
Could it be that it's trying to load tests from tests/fixtures/schema/testing_uppercase.json, even though there aren't any?

**Comment by bmcfee** [comment]
That's strange, since it shouldn't be loading any of the test data through pkg_resources.

Are you sure that things are installed properly (ie, `pip install -e .` from the tld)?

**Comment by justinsalamon** [comment]
That seems to have done the trick (even though all the requirements were already satisfied). Could it be because I hadn't run `setup.py develop` (which pip seems to have)?

**Comment by bmcfee** [comment]
Yup.  For future reference, `pip install -e .` will install the package locally without copying.  This way, any changes you make in the repo are immediately importable.  This is good for testing (compared to not installing at all) because it more accurately reflects how it will be used in the wild.

This is also why it's handy to use conda environments to distinguish between "stable" and "development" environments.

**Comment by justinsalamon** [comment]
roger that, cheers.
