### ISSUE TITLE
Conversion to and from MIDI

### ISSUE THREAD

**Issue by carlthome** [marl/jams#113]
Would it be possible to add utility functions for reading and writing to MIDI? I have a lot of datasets that still use MIDI for onset/pitch annotations (especially when data scraping online resources). I could add a pr if needed.

**Comment by justinsalamon** [comment]
Actually this is [already in the works](https://github.com/marl/jams-data/pull/13) as part of the jams-data repo (where all converters go), it's been a little dormant for a while but if there's a need I could get back on it.

The conversion itself is pretty much there, the pending issue is how to handle metadata, for which I already have some ideas (noted in the PR).

**Comment by carlthome** [comment]
Great news! Sorry for not searching properly.
