### ISSUE TITLE
Include jams-data as a submodule in the main jams repo?

### ISSUE THREAD

**Issue by urinieto** [marl/jams#114]
I think it would be nice to add a submodule to the [jams-data](https://github.com/marl/jams-data) repo inside the this main `jams` repo.

I recently did this with [msaf](https://github.com/urinieto/msaf/tree/0.1.0-dev) (look at the `datasets` folder). I'd be happy to create a PR for this in jams if you find it appropriate.

**Comment by bmcfee** [comment]
Why? Nothing in jams depends on jams-data.

**Comment by urinieto** [comment]
So that if you want to have some JAMS files to play around with once you cloned the `jams` repo, you could simply do it from the `jams` repo, instead of having to go and clone another repo in another folder.

**Comment by bmcfee** [comment]
Not sure that's something we really want though.  I figure most jams users will install via pip; cloning the repo should really only be for development.  That's just my 2 :heavy_multiplication_x:  :dollar: / :100: though.  Anyone else have opinions?

**Comment by justinsalamon** [comment]
Not sure I'd include jams-data as part of jams, but perhaps increasing the visibility of jams-data in the jams documentation (e.g. in the readme file) would be a good idea, as it seems many people aren't aware of the repo at all, some even asking about writing parsers that already exist.

**Comment by bmcfee** [comment]
Any objection to closing this out?

**Comment by urinieto** [comment]
None from me.
