### ISSUE TITLE
evaluation wrapper - sort segments by time

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#116]
It's not obvious to me whether this is a bug for JAMS or mir_eval, but when evaluating segment data, I got some nasty exceptions whenever the interval data was not ordered.

This is easily fixable by calling `annotation.data.sort_values('time', inplace=True)` before generating interval/values and calling mir_eval.

[tagging @craffel for insight]

**Comment by craffel** [comment]
What were the exceptions?

**Comment by bmcfee** [comment]
Migrating this to craffel/mir_eval#202 and closing out.  Pretty sure it's not a jams issue.
