### ISSUE TITLE
Upgrade script 0.1-0.2?

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#117]
Hey @justinsalamon @ejhumphrey @rabitt @urinieto 

We need a script to update old jams to new jams.  Doesn't someone already have one of these?

Relatedly: can we set aside a few minutes to get everything in jams-data up to the most recent jams version?  Currently, half the datasets are in the old format, and it's a total pain.

**Comment by justinsalamon** [comment]
I think I've migrated all datasets for which I've written parsers, but I'll double check. My generic MIDI2JAMS parser is still pending.

**Comment by urinieto** [comment]
I believe I migrated the segmentation datasets too.

**Comment by bmcfee** [comment]
Most of the chord sets are still in the old format.

But wasn't there a catch-all upgrade script somewhere?

**Comment by urinieto** [comment]
I thought there was such a script too. Can't find it. However, there's one
that goes from Jams2 to Jams1:
https://github.com/urinieto/msaf-data/blob/master/parsers/jams2_to_jams.py

Maybe this serves as a starting point for the Jams1 -> Jams2 script.

**Comment by bmcfee** [comment]
This seems unlikely to happen at this point.  Closing it out.
