### ISSUE TITLE
JObjects / Sandbox inspection

### ISSUE THREAD

**Issue by ejhumphrey** [marl/jams#129]
It'd be shiny to have `.get` accessors for JObjects / Sandboxes to support field testing and default values (like `dict`s), so that code can march along gracefully when a field doesn't exist. Current hack is to use `getattr()`, but that's somewhat gross.

this method would propagate to all children, which ... maybe doesn't matter? thoughts?

**Comment by bmcfee** [comment]
It would conflict with the fancy indexing for annotations, I think.
