### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#13]
I'm starting a new issue to manage namespace definition/schema construction.

[Tagging @ejhumphrey @urinieto @justinsalamon @rabitt @jonforsyth ]

To recap the (offline) discussion from this morning, a jams *namespace* will be used to define the syntax and (some) semantics of the `values` field for an observation array, as well as the preferred packing format (dense or sparse).

Rather than bake each namespace into the schema directly, we'll take a more modular approach, and allow each namespace to sit in its own json file.  This will serve to decouple task semantics from jams syntax, and allow users to extend or modify the collection of namespaces without modifying the schema.

I'm thinking that the namespace files can be loosely grouped by task, and structured in the package as
```
schema/namespaces
schema/namespaces/chord
schema/namespaces/chord/harte.json
schema/namespaces/tag
schema/namespaces/tag/open.json
schema/namespaces/tag/gtzan.json
schema/namespaces/tag/cal500.json
...
```

Each namespace object is a dict, keyed by its (unique) identifier.  As a simple example, here's the specification for an open vocabulary tag annotation:
```json
{
    "tag_open": {
        "value": {
            "type": "string"
        },
        "dense": false,
        "descrpition": "Open tag vocabularies allow all strings"
    }
}
```
Namespaces must define the following fields:
* `value` : schema-style type declaration to define the type of the value field
* `dense` : whether to store the observation array as a dense (column-wise) array or sparse (row-wise) array
* `description` : a short description of the namespace.

I've checked in a few examples already, demonstrating various characteristics:

* [melody_hz](https://github.com/marl/jams/blob/pandas/schema/namespaces/melody/hz.json)
  This one allows numeric observations with dense packing

* [chord_harte](https://github.com/marl/jams/blob/pandas/schema/namespaces/chord/harte.json) 
  This one allows string observations that validate against the chord-matching regular expression

* [tag_gtzan](https://github.com/marl/jams/blob/pandas/schema/namespaces/tag/gtzan.json)
  This one only allows strings from a pre-determined vocabulary

To flesh this out, we'll need to accomplish the following:

1. Specify a reasonable collection of namespaces for each task:
  * [x] beat
    * [x] position
  * [x] chord
    * [x] harte
    * [x] roman
  * ~~[ ] genre~~
  * [x] key
  * [x] pitch
    * [x] pitch_hz
    * [x] pitch_midi
    * [x] pitch_class
  * [x] mood
    * [x] mood_thayer : time-varying positional coordinates in valence-arousal space
  * [x] onset
  * [x] pattern
  * [x] segment
    * [x] isophonics
    * [x] TUT
    * [x] salami_functions
    * [x] salami_upper
    * [x] salami_lower
    * [x] open
  * ~~[ ] source~~
  * [x] tag
    * [x] gtzan
    * [x] cal500
    * [x] cal10k
    * [x] open
    * ... ?
  * [x] lyrics
2. Implement the namespace management system in pyjams
3. Start re-translating datasets

**Comment by bmcfee** [comment]
OPINIONS BELOW
--------------------------

* I think that 'genre' should be abolished, and the corresponding datasets reconstituted under 'tag_' namespaces, eg, 'tag_gtzan'.

* I also think that 'mood' should be more specific.  We can have 'mood_thayer' for valence-arousal time series, and 'tag_mood' for a fixed-vocabulary tag observations.

* Is `pitch` redundant with 'melody_hz'?

* What about 'note'?

**Comment by urinieto** [comment]
I have added a bunch of segment labels namespaces (everything in this commit a30487e453b07062c01437e5c93930230e911767).

Should we also have namespaces for the segment boundaries? I don't think it's necessary since it's pretty obvious what goes into the "start" and "end" times of a segment.

**Comment by bmcfee** [comment]
> Should we also have namespaces for the segment boundaries? I don't think it's necessary since it's pretty obvious what goes into the "start" and "end" times of a segment.

I think it's redundant/implicit, since the interpretation of segment boundaries depends on the labeling, eg, salami_large vs salami_small.  It's good to keep these coupled, IMO.

**Comment by bmcfee** [comment]
I've added a few more namespaces, and implemented some basic validation code (offline, will push when the dust settles).

So far, it's pretty simple to use for import.  Here's a quick and dirty example for chords

```python
>>> import pandas as pd
>>> chordfiles = sorted(glob.glob('/home/bmcfee/data/beatles_iso/chordlab/*/*/*.lab'))

>>> df = pd.DataFrame.from_csv(chordfiles[0], index_col=None, header=None, sep=' ')
>>> df.columns = ['time', 'duration', 'value']
>>> df['confidence'] = None
>>> df['duration'] -= df['time']
>>> jf = pyjams.JamsFrame.from_dict(df.to_dict())  # to do timevalue conversion
>>> sch = namespace_to_schema('chord_harte')
>>> try: 
...    for obs in jf.to_dict(orient='record'):
...        jsonschema.validate(obs, sch)
...    print 'PASS'
... except jsonschema.ValidationError as e:
...    print 'FAIL'
...    print e
'PASS'
>>> jf['value'][0] = 'not a chord'
>>> for obs in jf.to_dict(orient='record'):
...    jsonschema.validate(obs, sch)
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
...
ValidationError: 'not a chord' does not match u'^((N)|(([A-G][b#]*)((:(maj|min|dim|aug|maj7|min7|7|dim7|hdim7|minmaj7|maj6|min6|9|maj9|min9|sus4|sus2|5|1)(\\((\\*?([b#]*([1-9]|1[0-3]?))(,\\*?([b#]*([1-9]|1[0-3]?)))*)\\))?)|(:\\((\\*?([b#]*([1-9]|1[0-3]?))(,\\*?([b#]*([1-9]|1[0-3]?)))*)\\)))?((/([b#]*([1-9]|1[0-3]?)))?)?))$'
```

**Comment by bmcfee** [comment]
The above example got me thinking back to prior discussion about interpretation of the `confidence` field being task-dependent.  It would be pretty easy to hack this into the namespace spec, just like we currently have for defining the `values` field.

As a concrete example, the tempo estimation task defines two tempo measurements and a weighting term between them, eg:
```
60.5    121   0.35
```
to specify a tempo of `121` with `65%` bias, and `60.5` with `35%` bias.

This could be packed in a JamsFrame (jampacked?) as follows
```
time    duration        value   confidence
0       [track length]  60.5    0.35
0       [track length]  121.0   0.65
```
and the corresponding namespace file would look like
```json
{"tempo":
    {
        "value": {
                    "type": "number", 
                    "minimum": "0"
        },
        "confidence": {
                    "type": "float", 
                    "minimum": "0",
                    "maximum": "1"
        },
        "dense": false,
        "description": "Tempo measurements, in beats per minute (BPM)"
    }
}
```

Of course, more elaborate confidence schemata are possible, but this is a pretty simple case, and we basically get validation for free as long as we're doing value-validation.

What do yall think?

**Comment by justinsalamon** [comment]
At the risk of being stoned for thread-hijacking, I notice you're using [track length] for the duration of properties that are "time/duration" agnostic (in this case tempo, other examples could be genre, key, etc.). Did we agree on this convention? Is there a thread where this is being discussed? Wouldn't it be safer to have some type of NaN duration indicator so that the distinction between things that span time (e.g. a chord label) and things that don't (e.g. a genre label) is explicit?

**Comment by rabitt** [comment]
@bmcfee +1 confidence schema

**Comment by bmcfee** [comment]
f031a913a3f12a6b09529bd927e02d4b6e9e10c4 adds confidence to the tempo namespace.

**Comment by bmcfee** [comment]
The HAMR code sprint seems to have stabilized namespaces pretty well.  Validation now works, and we have a good set of namespace schema in place.

I discussed a possible namespace schema for the time-varying mood_xy data with folks at NEMISIG, and it sounds like packing valence and arousal as tuples into the `value` field will work fine.  JamsFrame supports this kind of functionality without further modification, so I think we're pretty well set.

**Comment by justinsalamon** [comment]
TODO with @rabitt: we need to discuss/sort-out the whole melody/note/pitch/f0 ambiguity stuff

**Comment by bmcfee** [comment]
> TODO with @rabitt: we need to discuss/sort-out the whole melody/note/pitch/f0 ambiguity stuff

Feel free to add sub-categories to the list above so we can check things off as we go.

**Comment by bmcfee** [comment]
41e2b60600784121bfb12053fa10b92dd733a773 adds thayer mood space models.

Note: these work with list-values in python, but not (yet) tuples.

**Comment by bmcfee** [comment]
It turns out that I don't actually understand music.  Who wants to write namespace schema(s) for key? @ejhumphrey ?

I grepped out the distinct values in the isophonics data, which amounts to:
```
Key	A
Key	Ab
Key	A:minor
Key	A:mixolydian
Key	B
Key	Bb
Key	Bb:minor
Key	B:minor
Key	C
Key	Cb
Key	C:minor
Key	C#:minor
Key	C#:modal
Key	D
Key	D:aeolian
Key	Db
Key	D:minor
Key	D:mixolydian
Key	E
Key	Eb
Key	Eb:minor
Key	E:major
Key	E:minor
Key	F
Key	F#
Key	F:dorian
Key	F:minor
Key	F#:minor
Key	G
Key	G:mixolydian
Key	N
Silence
```

I'm thinking that this could be an easy regexp in the style of chord_harte:
```
^N|([A-G][b#]?(:<MODE>)?$
```
where `<MODE>` is a disjunction of all the modes (does "all the modes" make sense?).  I would encode "Silence" as a null obsevation.

Do we need to have multiple key namespaces?  Do we need to support things like "melodic minor" vs "harmonic minor"?  Should we split off major-minor as a simplified namespace, or lump everything together in a master namespace?

Halp plz.

**Comment by bmcfee** [comment]
Should we remove the `source` namespace?  @rabitt says it doesn't make much sense.

**Comment by bmcfee** [comment]
I added a basic namespace for key-mode.  Someone with musical knowledge please fix it.

**Comment by urinieto** [comment]
I have added the pattern namespace. Please @bmcfee, take a look at it, since I'm not sure how to differentiate between float and int in the namespace (I simply used "number", as in the [schema file](https://github.com/marl/jams/blob/develop/schema/jams_schema.json)).

**Comment by bmcfee** [comment]
> I'm not sure how to differentiate between float and int in the namespace

http://json-schema.org/latest/json-schema-core.html#anchor8

Otherwise, looks good.  Can you cook up a trivial example and make sure that it validates?

**Comment by bmcfee** [comment]
(Documenting some in-lab conversations with @rabitt)

* `melody_*` should be renamed to `pitch`.  If you want special markers for "melody", it can be encoded in annotation metadata and retrieved by `search`.
* To support the rock corpus data, we'll need a "pitch class" namespace that can support key-centered annotations.  We settled on packing this as value-tuples of `(key, interval)`, where `key` is the root note, and interval is the number of steps away.
* For consistency with the pitch annotations, `chord_roman` will also have tuples of `(key, chord)`
* We still need a way to encode downbeats, and more generally, metrical position.  Rather than trying to shoehorn this into the beat namespace, we can instead have a namespace that encodes tuples `(position, measure number, #beats per bar, beat unit)`

In general, there's no way around slicing certain annotations into multiple jams Annotation objects.  In order to keep things straight, we should encourage the use of consistent AnnotationMetadata to make things searchable.

**Comment by justinsalamon** [comment]
> melody_* should be renamed to pitch. If you want special markers for "melody", it can be encoded in annotation metadata and retrieved by search.

I think Rachel and I were supposed to hash this one out but never got round to it. My 2c:
* Pros: melody is just a pitch sequence, so it makes sense to just have a generic pitch_*
* Cons: this will break consistency with both MIREX and mir_eval where melody stuff is called melody_\*. Melody is a particular enough pitch track to have received it's own name :) Thinking of the MIREX/mir_eval/JAMS ecosystem, using melody_* might be more consistent, and we could have pitch_* as well for any other pitch track. Internally they would be identical, but it would maintain the semantics used elsewhere.

**Comment by bmcfee** [comment]
> Melody is a particular enough pitch track to have received it's own name :) Thinking of the MIREX/mir_eval/JAMS ecosystem, using melody_* might be more consistent, and we could still have pitch_* for any other pitch track. Internally they would be identical, but it would maintain the semantics used elsewhere.

Right now, we have no integration with mir_eval on melody, since we hadn't settled on namespaces.

I think there's no problem using "pitch" as the namepsace selection and "melody" to interface with mir_eval.  Since the evaluation interface accepts Annotation objects as input, not JAMS, there is no need to modify any selection logic: you select which annotations you want first (say, by searching on "melody" in the metadata), and then call `jams.eval.melody(ref_ann, est_ann)`.

Of course, if mir_eval ever switches melody to pitch, we can switch over as well.

**Comment by justinsalamon** [comment]
It's been a while since I've look at the schema :S Which metadata field would the indication of melody go in? Do we have a consistent field for such an indication? If not it could end up being a bit of a mess... no?

Also, last time we'd settled on melody_hz. If we change it to pitch, it should probably be pitch_hz, since pitch on its own is ambiguous (pitch encoded how? hz / midi / etc...)

**Comment by bmcfee** [comment]
> It's been a while since I've look at the schema :S Which metadata field would the indication of melody go in? Do we have a consistent field for such an indication? If not it could end up being a bit of a mess... no?

`annotation_rules` seems appropriate, since it's a specific instruction being given to the annotator to select which pitch contour to annotate.

And yes, like I said, "melody_*" is now "pitch_*".

**Comment by justinsalamon** [comment]
> ```annotation_rules``` seems appropriate, since it's a specific instruction being given to the annotator to select which pitch contour to annotate.

Whilst ```annotation_rules``` is intended to document the annotation process, it feels risky to rely on people actually filling this field (especially for existing ported datasets). But perhaps my concern is misplaced - if I have a collection such as ADC04 (which only has melody annotation), I can just collect the annotations by the dataset name, right? @rabitt, how would you go about indicating melody annotation in MedleyDB for instance?

> And yes, like I ~~said~~ meant to say, `melody_*` is now `pitch_*`.

Doh.

**Comment by bmcfee** [comment]
> But perhaps my concern is misplaced - if I have a collection such as ADC04 (which only has melody annotations), I can just collect the annotations by the dataset name, right?

Absolutely: JAMS.search() allows arbitrary search fields, so you could easily match on collection name, if that's what you want.  (You can even provide arbitrary filter logic with a lambda function, if that's your jam.)  Collecting by dataset name will work fine for reference, but not estimations.

I think, in general, we have to rely on the user to know which annotations they care about, and leave it to them to decide how exactly to keep track of things.  Of course, we can provide useful prototype examples in the documentation.  I figure that most of the time, this won't be an issue.

**Comment by ejhumphrey** [comment]
>
> (You can even provide arbitrary filter logic with a lambda function, if
> that's your jam.)
>
​har. dee. har.​

**Comment by bmcfee** [comment]
Ok, we now have all of the initial namespaces (listed above) covered.

Are there any other tasks that need immediate integration, or shall we mark this as closed?

**Comment by bmcfee** [comment]
@urinieto do we actually need both `segment_isophonics` and `segment_open`?  They're functionally equivalent, and isophonics doesn't appear to have a consistent naming convention for segment labels.

**Comment by urinieto** [comment]
you're right. I guess we can ditch the isophonics one.
