### ISSUE TITLE
Support multiple JSON Schema Validator Backends?

### ISSUE THREAD

**Issue by ejhumphrey** [marl/jams#132]
As implicitly acknowledged in #46, validating against the JSON schema is expensive, slow, and when running things at scale, really making me think about skipping it, which is a red flag. If I'm thinking about bailing on validation, others aren't far behind me. 

I did a little digging, and it seems this is more a function of `jsonschema` being slow than schema validation being inherently slow. For example, this: https://github.com/epoberezkin/ajv#performance

Couple thoughts:
- I recognize that these are not Python libraries, but it demonstrates the variability in validator performance.
- The fastest one has a [command line interface](https://github.com/jessedc/ajv-cli) that we could consider wrapping. This wouldn't (and shouldn't) be the default validator, but multiple backends could allow for more flexible validator support.
- There don't actually seem to be many "native" options for JSON schema validation in Python, so wrapping one in another language might be simplest way to speed this up.

thoughts? complete heresy?

**Comment by bmcfee** [comment]
So, are you suggesting to make a python wrapper on ajv?  That sounds useful, especially if its api could look like jsonschema (or at least, close enough to be swappable).  Alternately, if it was done via some kind of javascript/node bridge (does this exist?) then it could persist some state so it's not rebuilding the whole validator every time it gets called.

I'd be open to using such a library in JAMS, but it would definitely complicate the dependency chain to have non-python dependencies.  OTOH, if the hypothesized pyajv included the full ajv source (which seems legit, given the MIT license on ajv), it could work.

**Comment by ejhumphrey** [comment]
> So, are you suggesting to make a python wrapper on ajv?

yeah, exactly.

> Alternately, if it was done via some kind of javascript/node bridge (does this exist?) then it could persist some state so it's not rebuilding the whole validator every time it gets called.

yeeaaaa I have no idea. Previous experience attempting to bridge scripting languages was ... not great ... so wrapping a CLI might be the easier out.

> OTOH, if the hypothesized pyajv included the full ajv source (which seems legit, given the MIT license on ajv), it could work.

Agreed. I'm curious if either of the `ajv` or `ajv-cli` projects would be keen to take on a python wrapper _in_ the project (probably the latter, if at all).

**Comment by bmcfee** [comment]
> so wrapping a CLI might be the easier out.

Sure... doesn't the cli require node (or something similar) though? I mean, the thing's written in js.



> 'm curious if either of the ajv or ajv-cli projects would be keen to take on a python wrapper in the project (probably the latter, if at all).

I kinda doubt it, at least within the minimal repo they have.  But I bet you could subtree the ajv-cli repo within a python package repo to make it easy to keep things synchronized.

**Comment by jdthorpe** [comment]
FYI, there's a thin wrapper for ajv [here](https://github.com/jdthorpe/ajvpy)

**Comment by bmcfee** [comment]
Is there still interest in this issue, or any viable alternative we could try out?

Ajvpy seems promising, but the pyv8 distribution seems to be fundamentally broken (no files uploaded for the latest ver on pypi; pip can only install v0.5 from 2009).  I have not been able to install it in any of my dev environments.  This makes me think it's a bad idea to have it as even an optional dependency.

**Comment by ejhumphrey** [comment]
there's definitely still interest for my part; I've found myself skipping validation (on at least reading) for speed. 

related: here's a caffeine induced idea that may or may not be terrible... what if we implemented a validation hash / caching scheme, where a checksum of a jams object is stored when successfully validated (per annotation? or whole thing?). The validation routine could look something like..

```python
def validate(jobj, *args, **kwargs):
    hash = func(jobj.dumps())
    if hash == jobj['__hash__']:
        return True
    else:
        is_valid = jobj.validate(*args, **kwargs)
        if is_valid:
            jobj['__hash__'] = func(jobj.dumps())
            return True
        else: 
            return False
``` 
There'd need to be some trickery around `dumps` returning only the schematized part of the object (so we could update the `__hash__` field without altering the checksum), but ... let's get past the proposal first.

**Comment by bmcfee** [comment]
You mean like #46 ?  I dug into it a bit last week, and I think it's a non-starter (details in thread).

**Comment by ejhumphrey** [comment]
kinda (didn't realize #46 existed..), although that looks like the joblib solution would be in-memory?

I'm proposing a persistent hash, like the one I gather you preferred ... this might get a little obvious, but explicit > implicit. 

I'm perfectly happy with a fragile / holistic hash over the object, rather than trying to validate subcomponents. In my experience, most of time lost to validation occurs when reading Jams objects / files that never change. This is why I've been somewhat okay with not validating on load (validate on write and then assume the best). Therefore, if an object's been written with a hash, that token would indicate it was at some point validated, and if you get the same hash back, then it also hasn't changed (and thus the object is still valid). 

This doesn't seem too bad? There'd be no need for sub-object consistency, because a global hash acts as a logical short circuit on (in)validity... right?

**Comment by bmcfee** [comment]
Ah, I hadn't understood that.

Maybe before getting into this, it would help to profile the validation just to see if there's anything smarter we could do?

Sub-component validation makes me a bit nervous because the schema is holistic to start with, so we'd have to do some hackery to make it work piecemeal.

**Comment by ejhumphrey** [comment]
Ya, to be perfectly clear, I also don't want to dabble in subcomponent / arbitrary `JObject` validation ... but I think it might make sense to do this at the `Annotation` level rather than a `Jams` object, since the former tend to be more like documents, and the latter more like containers.

as for profiling ... I read Jams files *far* more than I write / modify them, so therefore the majority of my time validating Jams files is wasted (converging to "all of my time" as t -> inf). 😄

**Comment by bmcfee** [comment]
> as for profiling ... I read Jams files far more than I write / modify them, so therefore the majority of my time validating Jams files is wasted (converging to "all of my time" as t -> inf).

Har. :roll_eyes: 

What I meant was: it's worth looking into where the hot spots are in validation.  Maybe the time is spent primarily in (de)serialization?

If I had to guess, I'd guess that this part: https://github.com/marl/jams/blob/master/jams/core.py#L770-L771 is a substantial bottleneck, especially for dense arrays, since it validates each observation independently.  I suppose that could be accelerated by serializing the whole observation array first, and then validating it against a dynamic schema for arrays of that namespace.

**Comment by bmcfee** [comment]
Quick benchmark on a random example from medleydb:
```python
In [1]: import jams
In [2]: J = jams.load('/home/bmcfee/git/jams-data/datasets/MedleyDB/KarimDouaidy_Hopscotch.jams', validate=False)
In [3]: %timeit J.validate()
51.8 s ± 619 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Profiling it reveals that obs-independent validation is in fact a huge problem: ~200K calls to `validate` in this example.

Vectorizing the annotation validation should provide a substantial speedup; I'll give that a spin and report back.

**Comment by bmcfee** [comment]
Narrowing this down to one dense annotation, element-wise validation profiles as:
```python
In [23]: %timeit J.annotations[1].validate()
Out [24]: 25.4 s ± 1.12 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Vectorized validation profiles as:
```python
In [24]: %%timeit
data = jams.core.serialize_obj(list(J.annotations[1].data))
sch = jams.schema.namespace_array(J.annotations[1].namespace)

jsonschema.validate(data, sch)
Out [24]: 1.62 s ± 43.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Swapping out `data` from an in-memory list to a generator brings it down a little more (and saves memory):
```python
data = [jams.core.serialize_obj(_) for _ in J.annotations[1].data]
[snip]
1.58 s ± 18.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by bmcfee** [comment]
Returning to the full jams example above, we now get
```python
In [1]: import jams
In [2]: J = jams.load('/home/bmcfee/git/jams-data/datasets/MedleyDB/KarimDouaidy_Hopscotch.jams', validate=False)
In [3]: %timeit J.validate()
7.1 s ± 601 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Compared to ~52s per loop previously.

Here's a random example with sparse annotations in isophonics:
```python
In [2]: J = jams.load('/home/bmcfee/data/beatles_iso/jams/Beatles/06_-_Rubber_Soul/02_-_Norwegian_Wood_(This_Bird_Has_Flown).jams', validate=False)
In [3]: %timeit J.validate()
51.3 ms ± 804 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
And on the current master (old version), we get:
```python
In [2]: J = jams.load('/home/bmcfee/data/beatles_iso/jams/Beatles/06_-_Rubber_Soul/02_-_Norwegian_Wood_(This_Bird_Has_Flown).jams', validate=False)
In [3]: %timeit J.validate()
261 ms ± 3.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
So we can generally expect a 4-8x speedup just from this hack.  @ejhumphrey would that sufficiently help on your end?

**Comment by bmcfee** [comment]
Is there any reason to keep this open, or can we close it out as a non-fixer?
