### ISSUE TITLE
pandas 0.20 compatibility

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#147]
This will be fun.  Not sure how deep this all goes, but I think we're in for some compatibility headaches.

```python
In [3]: J = jams.load('trapped.jams')
/home/bmcfee/git/jams/jams/core.py:1852: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access Timedelta as pandas.Timedelta
  if isinstance(obj, pd.tslib.Timedelta):
```

**Comment by bmcfee** [comment]
For reference, here are the [release notes](http://pandas.pydata.org/pandas-docs/stable/release.html#pandas-0-20-0-0-20-1).

Running locally, it's a total disaster:
```
Ran 759 tests in 23.096s

FAILED (failures=271)
```

**Comment by justinsalamon** [comment]
😱😱😱

**Comment by bmcfee** [comment]
It looks like these all(?) stem from the same issue inside `JamsFrame.add_observation` that is not allowing us to append strings into the value column.

**Comment by bmcfee** [comment]
Punting upstream to https://github.com/pandas-dev/pandas/issues/16309 , but I don't think we should wait on pandas to fix it for us.
