### ISSUE TITLE
Consistent filename/namespace names

### ISSUE THREAD

**Issue by justinsalamon** [marl/jams#163]
Right now namespace filesnames can be different from the namespaces they contain. I think this can get quite confusing and would propose to use consistent namespace/filenames.

For example, the `contour_hz.json` file contains a namespace `pitch_contour`, which is extra confusing because we have a bunch of namespaces for representing pitch. Pitch can be represented either as note or contour, and those in turn are expressed in units of hz/midi. `pitch_contour` doesn't make it explicit that the unit is in hz. Also, for all the other pitch namespaces the filename *does* match the contained namespace.

**Comment by bmcfee** [comment]
I think this is not a huge deal.  The filenames are for internal use only, and no user-facing code should even be aware that namespace definitions live in json files at all.

**Comment by bmcfee** [comment]
@justinsalamon Can we mark this as `won't-fix` and close it out?
