### ISSUE TITLE
Do we still need top-level groupings of annotations?

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#17]
Do we, @ejhumphrey @justinsalamon @urinieto ?

At this point, they're redundant with the namespace fields.

Eliminating the top-level groupings would simplify the search logic #15 and make the schema automatically extensible for new tasks by adding new schema entries.

What we lose is a little coherence/human readability, but it's still encoded by the namespace field, so maybe it's not so bad?

Vote?

**Comment by rabitt** [comment]
+1

**Comment by ejhumphrey** [comment]
I vote that we don't; however, there's no reason we can't provide
convenience properties / methods to simplify access.

e

**Comment by bmcfee** [comment]
The convenience method right now would look like

```python
>>> beats = my_jam.search(namespace='beat')
```

We could provide sugar for that query, but I think it's simple enough that maybe we don't need to?

**Comment by justinsalamon** [comment]
As long as it's documented with a couple of examples to get users started I think that's probably enough, with the bonus that you mentioned of making the format extensible without needing to modify the schema
