### ISSUE TITLE
support jsonschema >= 3.0

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#193]
Dropping this here until we have time to deal with it properly.  JAMS tests currently fail on jsonschema 3.0.0a2.

**Comment by bensteers** [comment]
Can confirm this issue (with 3.0.0a3). Downgrading to 2.6 fixed it. Thanks for the tip!

**Comment by bmcfee** [comment]
Thanks for noting that it's still a problem -- I think it's going to continue being a problem in 3.0 final.

We will need to get out ahead of this at some point -- any takers?

**Comment by bmcfee** [comment]
This issue has suddenly become a bit more severe, as many other packages (including jupyterlab) now require jsonschema >= 3.
