### ISSUE TITLE
Install fails on Python 3.12: `imp` Module Missing

### ISSUE THREAD

**Issue by robaerd** [marl/jams#214]
The `imp` package, used in `setup.py`, is no longer available in Python 3.12  (see [docu](https://docs.python.org/dev/whatsnew/3.12.html#imp)).

As a result, executing `pip install` under Python 3.12 fails with:

```
ModuleNotFoundError: No module named 'imp'
```

**Comment by bmcfee** [comment]
Thanks for noting this.  It should be an easy enough fix, but i don't have the bandwidth to implement it right now.  Would you be interested / willing to make a PR for this?

**Comment by robaerd** [comment]
Sure, I will give it a try!

**Comment by rubencart** [comment]
Would be nice if this got fixed soon!

**Comment by bmcfee** [comment]
@rubencart as noted in the PR #215, this is blocked at the moment by getting a new mir_eval release out. I'm working on that when I can.

**Comment by rubencart** [comment]
OK thanks! Can I install from source with the fix for now, or will the mir_eval dependency prevent that from working?
