### ISSUE TITLE
documentation update

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#23]
we need to update the documentation to match the new version.

**Comment by bmcfee** [comment]
I've done a full pass of restructuring and updating docstrings.  I think we're in good shape for the API reference.

The next step, open to anyone that wants to take it, is updating the quickstart documentation.

We also have automatic doc builds on readthedocs, but they are currently broken since RTD uses sphinx 1.3, which fails on autosummary for some reason.

**Comment by bmcfee** [comment]
And now for the really fun to-do on documentation: namespaces!

 - [ ] beat_beat
  - [ ] beat_position
  - [ ] chord_harte
  - [ ] chord_roman
  - [ ] key_key_mode
  - [ ] lyrics_lyrics
  - [ ] mood_thayer
  - [ ] onset_onset
  - [ ] pattern_jku
  - [ ] pitch_class
  - [ ] pitch_hz
  - [ ] pitch_midi
  - [ ] segment_open
  - [ ] segment_salami_function
  - [ ] segment_salami_lower
  - [ ] segment_salami_upper
  - [ ] segment_tut
  - [ ] tag_cal10k
  - [ ] tag_cal500
  - [ ] tag_gtzan
  - [ ] tag_medleydb_instruments
  - [ ] tag_open
  - [ ] tempo_tempo

**Comment by justinsalamon** [comment]
Is there an existing example of what this should look like?

**Comment by bmcfee** [comment]
> Is there an existing example of what this should look like?

Nope!  And we can't quite autodoc it, since a) json doesn't have comments, and b) sphinx wouldn't parse them out automatically anyway.

It'll just have to be a section within the jams docs, with subsections for tasks, and subsubsections for individual namespaces.

Each namespace should have an explanation of the value and confidence fields, expected interpretation of time+duration, and any additional expected semantics.

I'll bang out the skeleton for this and add a couple of examples to get us started.

**Comment by justinsalamon** [comment]
:+1:

**Comment by bmcfee** [comment]
Ok, I've pushed up a skeleton and written documentation for the beat types.

This should be enough to get everyone started on their respective tasks.

**Comment by bmcfee** [comment]
@ejhumphrey I added a quick hack of chord_roman's namespace, but it's missing some things.  Please correct.

**Comment by bmcfee** [comment]
@urinieto Can you chip in a namespace doc for `pattern_jku`?

@justinsalamon Can you do `pitch_hz`?

**Comment by justinsalamon** [comment]
@bmcfee have a look, it's a little verbose but I have tried to explain the conventions as succinctly as possible

**Comment by bmcfee** [comment]
Seems good.  We could probably trim it a little and reformat, but the entire namespace docs need an edit pass anyway.

**Comment by urinieto** [comment]
Ok, I just finished my part for the `pattern_jku`.

**Comment by bmcfee** [comment]
After resolving #53, I think we're good to go (functionally) on this one.

I'll give the documentation a final editorial pass, but otherwise I think we're ready for 0.2.0!

**Comment by bmcfee** [comment]
0f6e0657d0416aaeb082446d312a5dc280d94e04 adds a new doc page that contains a fully worked example using librosa to estimate beats and tempo, and store the results in a .jams file.

Are there any other use-cases that could benefit from a fully-worked example script?  Maybe evaluation?

**Comment by justinsalamon** [comment]
> Are there any other use-cases that could benefit from a fully-worked example script? Maybe evaluation?

Definitely evaluation (with mir_eval), and perhaps also parsing an existing dataset into jams? Or just some type of csv format into jams, since once of jams's main purposes is to store annotations and there still isn't any annotation software out there that will output directly into jams format (should we revisit the conversation with Chris about SV at some point?)

**Comment by urinieto** [comment]
+1.

Also clearly mention/link the jams-data repo from where to get the already
parsed datasets.

**Comment by bmcfee** [comment]
> Definitely evaluation (with mir_eval), and perhaps also parsing an existing dataset into jams?

I think the latter is best left to the `jams-data` repo.

A jams-to-jams evaluation example would be easy though.


> Or just some type of csv format into jams,

That might be doable.  I worry that providing a coherent example would require too much special-case hackery for data cleaning though, and distract from the main points.  I tend to think the quickstart and beat tracking examples are enough to illustrate the process, and reading CSV isn't really our job.  (If you can read csv, it should be obvious how to drop that into the existing examples.)



> Also clearly mention/link the jams-data repo from where to get the already
> parsed datasets.

Do we want to do this already, or wait until that repo is done?  I'd rather not link to docs/data that are out of date.

**Comment by urinieto** [comment]
Do we want to do this already, or wait until that repo is done? I'd rather
not link to docs/data that are out of date.

I would at least mention the repo, and make sure to say it is still a work
in progress.

**Comment by bmcfee** [comment]
Done and done.  We now have an example that shows how to parse isophonics chords into jams, and links out to jams-data.

**Comment by justinsalamon** [comment]
:+1: :+1: :+1:

**Comment by bmcfee** [comment]
Anything else? I'd like to push this out by the self-imposed deadline next week.

**Comment by urinieto** [comment]
I think that should be it!
