### ISSUE TITLE
rewrite unit tests

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#26]
... since the schema's all different, and much of the (python) codebase has been simplified or rewritten, this is probably necessary.

@ejhumphrey Any objection to switching from `unittest.TestCase` objects (old and busted) over to nosetest functions (new hotness)?  This will make tests easier to write, and play nicely with #25 .

**Comment by bmcfee** [comment]
Sketching out a plan for test design:

- [ ] JObject
  - [ ] serialization, deserialization
  - [ ] equivalence testing
  - [ ] dict-like methods
  - [ ] search
- [ ] Sandbox
  - [ ] just test for construction; all else inherits from JObject
- [ ] JamsFrame
  - [ ] construction, conversion
  - [ ] add_observation
  - [ ] interval_values conversion
  - [ ] serialization (sparse and dense)
- [ ] Annotation
  - [ ] construction
  - [ ] append
- [ ] Curator
  - [ ] construction
- [ ] AnnotationMetadata
  - [ ] construction
- [ ] FileMetadata
  - [ ] construction
- [ ] AnnotationArray
  - [ ] construction
  - [ ] search
  - [ ] serialization
- [ ] JAMS
  - [ ] construction
  - [ ] load
  - [ ] save
  - [ ] add
  - [ ] validate
- [ ] pyjams functions
  - [ ] load
  - [ ] append
  - [ ] load_lab
- [ ] Utilities
  - [ ] timedelta_to_float
  - [ ] serialize_obj (should be implicit from JamsFrame tests)
  - [ ] read_lab (do we still need this?)
  - [ ] load_textlist
  - [ ] expand_filepaths
  - [ ] smkdirs
  - [ ] filebase
  - [ ] find_with_extension
  - [ ] match_query (semi-redundant with JObject.search test)
  - [ ] query_pop (also semi-redundant with JObject.search test)

**Comment by urinieto** [comment]
Nosetests +1

This test list is.... well, I have no words, I'm so impressed.

**Comment by bmcfee** [comment]
> This test list is.... well, I have no words, I'm so impressed.

save being impressed for after we've implemented it!

**Comment by ejhumphrey** [comment]
sounds great; any preferred examples to share of this in practice? or any
ole google search will do?

**Comment by bmcfee** [comment]
> any preferred examples to share of this in practice?

nose is super easy to use, but librosa has tons of (not so clean) [examples](https://github.com/bmcfee/librosa/blob/develop/tests/test_met_features.py)

**Comment by bmcfee** [comment]
In the process of implementing tests, I've been doing a little refactoring and simplification.

Specifically:

- All `pyjams`util functions not relating to file IO have been moved into `pyjams`
- `namespace` (now `ns`) functions no longer depend on `pyjams` or `util`.  Namespace schema are now loaded in the top-level module after all submodules have been imported.
- This means that the submodule dependency chain now looks like:
  - `ns` < `pyjams` < `util`

As such, I've moved the lab->annotation loader from `pyjams` into `util`, where it makes more sense.

So, the question for all of you is:
- do we still need the previous `read_lab`?  It seems more brittle than the pandas-based parser in `import_lab`.  (Once again, [never write csv parsers yourself](http://tburette.github.io/blog/2014/05/25/so-you-want-to-write-your-own-CSV-code/).)
- what about `load_textlist`?

**Comment by urinieto** [comment]
We do need a function to convert labs to jams. As long as it works, I don't care whether we use the current `read_lab` or not (sorry, is that what you're asking?).

**Comment by bmcfee** [comment]
Yes; to clarify, we currently have two:

- `read_lab` reads csv directly, and returns a flat array.  This function exists in the initial jams release.
- `import_lab` uses pandas csv loader, requires a target namespace, and constructs an Annotation object.  Optionally, it can append directly into an existing JAMS.  I added this function to streamline the process and work around some of the inevitable quirks of csv parsing.

I'm advocating dropping `read_lab`, but if there's a compelling reason to include our own csv/tsv->array parser, I'm open to keeping it.

**Comment by urinieto** [comment]
I'd rather not use a custom implementation if another one already exists
in, e.g., pandas.

**Comment by justinsalamon** [comment]
pandas +1

**Comment by bmcfee** [comment]
Coming back to this thread now.

What are people's thoughts on dropping load_textlist as well?  It's a one-liner that gets used twice in the (old) import scripts.  It sucks an entire text file into an array of strings, in memory.

I'd like to drop it, since it's A) simple enough to reimplement as needed (with increased clarity in the resulting code), and B) kind of a bad pattern, since it could crash out of memory if executed on a very large file.  I think, in all cases, we can replace it with calls to pandas csv/table parsers with no loss of functionality.

**Comment by ejhumphrey** [comment]
++

**Comment by urinieto** [comment]
++ too

**Comment by justinsalamon** [comment]
:+1:

**Comment by bmcfee** [comment]
Do we really need the 'jams.append()` function?  It seems to do too much: load, append, save..  I would prefer to factor out the load/save (already done) and just have a single function that appends one jam to another.

(Again, this is in the interest of simplifying the API and unit tests.)

**Comment by justinsalamon** [comment]
+1

**Comment by urinieto** [comment]
I would also support this. However, I would like to sit down with you
because I'm lost about the state of things with JAMS, and I would really
like to contribute.

**Comment by bmcfee** [comment]
Ok folks:

I've started pushing up some namespace validation tests.  They're super easy to write, but there are a lot of them, so help would be appreciated.

Existing examples are to be found in `jams/tests/namespace_tests.py`.

Some basic guidelines:

* Include both pass and fail cases
* If your namespace includes string values, be sure to try with both str and unicode
* If your namespace has object or array values, be sure to try with missing fields or wrong-length arrays
* If your namespace defines a confidence schema, test it

And, because I'm such a benevolent dictator, I made homework problems for everyone!

---
# Assignments

* @urinieto - segment_*, pattern_jku
* @rabitt - pitch_class, chord_roman,  key_mode
* @justinsalamon - pitch_* (except class)
* @ejhumphrey - chord_harte, tag_*
* @bmcfee - beat_*, lyrics, tempo, mood_thayer, onset

**Comment by bmcfee** [comment]
In the course of writing namespace tests, I uncovered a fun bug in the serialization logic.

JObject.__json__ was (intentionally) skipping over fields whose values evaluated to False, which includes empty strings and zeros.  When you serialize the object, this omits several fields from the resulting dictionary structure, including things like `FileMetaData.release` and `Curator.email`.  Then, when you validate the entire object, since these fields are required, it barfs.

I've fixed it so that even empty fields are returned in the structure serialization.  This inflates the object on disk somewhat, but improves safety since we can guarantee that all fields are defined (if not populated).

**Comment by urinieto** [comment]
Nice.

**Comment by urinieto** [comment]
I just realized that the JAMS don't validate now if the duration of the
file doesn't exist in the file_metadata field. What if we don't really have
this info? (e.g., it is missing in some of the SALAMI songs listed in the
metadata.csv file).

**Comment by bmcfee** [comment]
> What if we don't really have
> this info? (e.g., it is missing in some of the SALAMI songs listed in the
> metadata.csv file).

You should be able to set it to `np.nan` in this case.  But don't all of the salami annotations have end-of-track event markers?

**Comment by urinieto** [comment]
Unfortunately, these end-of-track event markers are not always correct
(e.g., see track number 10).

**Comment by bmcfee** [comment]
> Unfortunately, these end-of-track event markers are not always correct
> (e.g., see track number 10).

I looked at track 10 and don't entirely understand the problem?  Yes, many of the annotations give different end time, but they're pretty close.  Why not just take the max of candidate end times as an estimate?

**Comment by urinieto** [comment]
Oh yes, you're right. I misread the annotations. Ok, so I will go ahead and
add the max estimate to the duration field in the metadata in the SALAMI /
Isophonics parser.

**Comment by justinsalamon** [comment]
Do we have any jams files that validate against the latest schema kicking around anywhere? Or a quick way to randomly generate some? Sheesh, it's been a while...

**Comment by bmcfee** [comment]
> Do we have any jams files that validate against the latest schema kicking around anywhere? Or a quick way to randomly generate some?

The SMC examples should validate.  There's also one copied over into `test/fixtures` that I use in the generic unit tests.

If you want to generate random ones, check [this](https://github.com/marl/jams/blob/develop/jams/tests/namespace_tests.py#L39-L50) for an example of how.  For the namespace tests, you only need to make Annotation objects, not full JAMSes.

**Comment by justinsalamon** [comment]
Trying to write a test for pitch_hz. Neither of the following two validate (I wasn't sure how to build a dense annotation since pitch_* seems to be the only case?):
```python
def test_ns_pitch_vz_valid():
    
    ann = Annotation(namespace='pitch_hz')
    
    for time in np.arange(5.0):
        ann.append(time=time, duration=0.0, value=100.0, confidence=None)
    
    ann.validate()
```
And:
```python
def test_ns_pitch_vz_valid():

    ann = Annotation(namespace='pitch_hz')
    
    seq_len = 5
    time = np.arange(seq_len)
    duration = np.zeros(seq_len)
    hz = np.random.uniform(-22050., 22050., seq_len)
    confidence = np.array([None]*seq_len)
    ann.append(time=time, duration=duration, value=hz, confidence=confidence)

    ann.validate()
```
Any ideas?

**Comment by bmcfee** [comment]
Super weird; I'm getting the same thing.

If I turn off strict validation, I get the following warning:

```python
In [18]: ann.validate(strict=False)
/home/bmcfee/git/jams/jams/pyjams.py:775: UserWarning: 'duration' is not of type u'object'
```

Will investigate later...

**Comment by justinsalamon** [comment]
Not sure if related, but when I create a pitch_hz annotation, the duration field gets converted into days. Could it be that duration is converted into some time-object that is not allowed by a dense annotation?

**Comment by bmcfee** [comment]
> Not sure if related, but when I create a pitch_hz annotation, the duration field gets converted into days. Could it be that duration is converted into some time-object that is not allowed by a dense annotation?

No, that's just how timedelta fields get repr'd when the value is 0 and there's no other values to set an appropriate scale (ie seconds).  The objects do serialize correctly.

You're right that it has to do with dense-vs-sparse serialization though:
```python
In [6]: ann.data.dense = False

In [7]: ann.validate()
Out[7]: True
```

I think this is entirely down to the `validate` method, and not a problem with the serialization itself.  I'll dig into it though.

**Comment by bmcfee** [comment]
> I think this is entirely down to the validate method, and not a problem with the serialization itself. I'll dig into it though.

aha!  [Yep](https://github.com/marl/jams/blob/develop/jams/pyjams.py#L768). We are implicitly assuming a SparseObject serialization that can bet iterated over record-wise in this logic.  This is easily fixable.

**Comment by bmcfee** [comment]
17d510f should fix this error via some list comprehension wizardry.

**Comment by justinsalamon** [comment]
```pitch_hz``` allows negative values due to the "x<=0 implies unvoiced" convention. Do we want to keep this convention for ```pitch_midi```? I'm not sure how an actual midi synth would handle negative note values, and it definitely doesn't use "0==silence". On the other hand, if we disallow these cases, then conversion between ```pitch_hz``` and ```pitch_midi``` becomes non-trivial.

**Comment by bmcfee** [comment]
> Do we want to keep this convention for pitch_midi?

I would say no, since negative midi numbers are technically possible.  For midi-type pitch annotations, I would expect silence to be indicated by the lack of annotation.

**Comment by justinsalamon** [comment]
but how would the lack of annotation be represented in a dense jams?

**Comment by bmcfee** [comment]
> but how would the lack of annotation be represented in a dense jams?

Dense events still have duration, so I don't see a problem here.

**Comment by justinsalamon** [comment]
>Dense events still have duration, so I don't see a problem here.

In the case of melody (pitch_hz) since the events happen on a uniform time grid the duration values are not expected to carry any meaningful information (they can all be 0 for example) - so you can't really use the duration to encode silence for dense annotations (at least not the way they are set up right now)

**Comment by bmcfee** [comment]
[documenting offline conversation with @justinsalamon]

* There is no difference between dense and sparse types in JAMS; the distinction only exists when objects are serialized.
* pitch_hz-type annotations are often used as samples of a (persumably) continuous F0 contour.  Assumptions of continuity are implicit, and the sample times typically correspond to centers of windows, rather than the leading edge of an interval over which the annotation applies.  As such, the duration field has no meaning, and should be set to 0.
* I whined a whole bunch about implicit assumptions in annotation formats, and advocated for not imposing any semantics on pitch_hz annotations.  The semantics should be encoded in the `annotation_rules` field.
* since pitch_midi is for notating discrete events, rather than sampling contours (as in pitch_hz, usually, i guess), it does not necessarily make sense to convert between the two.

**Comment by bmcfee** [comment]
@rabitt can you link the site you mentioned for generating positive/negative examples from a regexp?

**Comment by rabitt** [comment]
@bmcfee 
http://fent.github.io/randexp.js/

**Comment by bmcfee** [comment]
I took the liberty of finishing the `pattern_jku` tests...

and we've got full tests!  Closing this one out.

**Comment by urinieto** [comment]
Thanks titan!
