### ISSUE TITLE
Why does JObject inherit from object instead of dict?

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#27]
(paging @ejhumphrey )

Legit question, I'm curious if this was a conscious decision, and if so, what the reasons are/were.

Seems like inheriting from dict would let us ditch several one-liners which reimplement (most of) the dict interface?

**Comment by ejhumphrey** [comment]
This is a gardening issue... What started as an object evolved into a dict,
and it's totally sane / reasonable to consolidate now.

**Comment by bmcfee** [comment]
Right.

I think, once #26 is settled, that I'll rewrite JObject to inherit from dict.  There should be no change in functionality, and it should allow us to cut down some redundant code and simplify tests.

**Comment by bmcfee** [comment]
This actually seems unnecessary in retrospect.  The dict-interface is really only helpful for serialization, and otherwise we really want an object/named tuple style interface.

Closing this one out.
