### ISSUE TITLE
JAMS structure: Task-major vs Annotation-major

### ISSUE THREAD

**Issue by ejhumphrey** [marl/jams#3]
The initial proposal suggested that the JAMS hierarchy be task-major, as follows:

```
JAMS object/
    beat/
        annotation0/
            annotation_metadata/
            data/
                event
                ...
    chord/
        ...
    ...
```

I'm concerned that this isn't very future proof, and presents some practical issues:
1. Though annotations have been constrained to single "tasks" in the past, I'd contend this is more a function of conventional research methodology than how things should be done going forward. Carving out concept from the start pre-supposes that (a) every annotation you collect should serve an existing task and (b) these observations are somehow independent of each other. 
2. A single annotation containing information for multiple "tasks" must either (a) be divided when writing to file, and all annotation metadata must be duplicated, or (b) written into a separate top-level bucket linked via unique annotation keys. In the former scenario, it becomes possible for the same information to become inconsistent if one of the annotations is modified without the rest. In the latter, data integrity is forced to rely on linking conventions which, in JSON, is somewhat of a hack. Either way, this arguably results in a deficient representation, because you undermine the ability to enforce the schema.

Two alternatives include "Annotation-major, task-minor" or "Annotation-major, task-agnostic".

In "Annotation-major, task-minor", the structure would look like the following:

```
JAMS object/
    annotation0/
        annotation_metadata/
        beat/
            observations/
                interval
                ...
        chord/
            ...
        ...
    ...
```

In this case, the entire annotation is kept together, and the data are grouped internally by task. However, what I would love to prevent more than anything is the wonky scenario where "genre" and "tags" and "mood" and "usage" are different buckets. They're all just tags (and, more often than not, unfortunate ones at that). But this is a slippery slope, because, by the same logic, so are chord labels ... and so are structure labels, and beats, and onsets, and, well, just about everything except for melody. And then what's the point of splitting them out? They're all the same datatype with different namespaces / meanings. What's more, I don't know that we want to bake this namespace structure into the format, because it's not all that flexible should the schema need to evolve.

What does seem more flexible, is to introduce namespaces internal to the observations themselves and have either "type-minor" (group by schema type) or "type/task-agnostic" grouping inside of an annotation. Ignoring usability for a moment and focusing solely on forwards / backwards format compatibility, it seems this gives JAMS the best chance to evolve gracefully over a decade. 

Arguably, the file format / schema should be focused on being strict today and flexible tomorrow, while the programmatic interface / API should be easy to use, always. But who knows, maybe there's a compromise to be made here.

**Comment by bmcfee** [comment]
I think this one is resolved now.  Can we close it?
