### ISSUE TITLE
JAMS object not JSON serializable?

### ISSUE THREAD

**Issue by urinieto** [marl/jams#30]
I've been trying to update the SALAMI parser to support the current version of JAMS and SALAMI v2.0.

However, I get the following error when trying to [write the JAMS file into a new file](https://github.com/marl/jams/blob/develop/parsers/salami_parser.py#L170):

```
Traceback (most recent call last):
  File "./salami_parser.py", line 211, in <module>
    process(args.in_dir, args.out_dir)
  File "./salami_parser.py", line 189, in process
    os.path.basename(metadata[0]) + ".jams"))
  File "./salami_parser.py", line 170, in create_JAMS
    json.dump(jam, f, indent=2)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <JAMS: sandbox, annotations, file_metadata> is not JSON serializable
```

I believe I might be doing something wrong when creating the new JAMS object. Or maybe this has something to do with #27?

**Comment by ejhumphrey** [comment]
hrm ... a couple thoughts.
1. Things changed so we could have safe overload the built-in JSON library safely, and thus you can't directly use JSON to do your serialization.
2. Therefore, don't roll your own file-writing​. Use [JAMS.save](https://github.com/marl/jams/blob/develop/jams/pyjams.py#L807), or, if you must, ```json.dump(str(my_jam), fp)``` or ```json.dump(my_jam.dumps(), fp)```.

Also, I thought we had a counterpart pyjams.dump, matching [pyjams.load](https://github.com/marl/jams/blob/develop/jams/pyjams.py#L132), but there doesn't seem to be (anymore?). @bmcfee, do you have any insight here?

**Comment by urinieto** [comment]
Aw yes, ```JAMS.save``` fixes it.

Thanks!

**Comment by bmcfee** [comment]
> 1. Things changed so we could have safe overload the built-in JSON library safely, and thus you can't directly use JSON to do your serialization.

We should still find a way to make this work though.

> 2. Therefore, don't roll your own file-writing​. Use JAMS.save, or, if you must, json.dump(str(my_jam), fp) or json.dump(my_jam.dumps(), fp).
> 
> Also, I thought we had a counterpart pyjams.dump, matching pyjams.load, but there doesn't seem to be (anymore?). @bmcfee, do you have any insight here?

This may have gotten nuked in my housecleaning party.  We should have at least an alias to dumps(), but it should be a JObject class method, not a pyjams function.
