### ISSUE TITLE
Rewrite Parsers

### ISSUE THREAD

**Issue by urinieto** [marl/jams#31]
It is time to rewrite the dataset parsers, so that they work again with the current JAMS version.

- [ ] ADC2004Melody
- [ ] Billboard
- [x] Isophonics
- [x] JKU Patterns
- [ ] MedleyDB
- [ ] MIREX05Melody
- [ ] Rockcorpus
- [x] SALAMI
- [x] SMC
- [ ] TMC323
- [ ] CAL500
- [ ] CAL10K
- [ ] MSD
- [ ] IRMAS

@bmcfee already (re?)wrote the [SMC one](https://github.com/marl/jams/blob/develop/parsers/smc_parser.py), and I'm working on SALAMI and Isophonics.

I'm also gonna assign this to some of you, because my roots come from Spain, and we are used to [dictatorship](http://en.wikipedia.org/wiki/Francisco_Franco)[(s)](http://en.wikipedia.org/wiki/Philip_V_of_Spain) there.

**Comment by bmcfee** [comment]
Threadjacking

I'd like to propose we rebase the parsers and translated annotations out to a separate repository/module `jams-parsers`.  These things will in general be much more volatile than the core jams library, and we shouldn't need to tie versioning between the two.

I don't mind if this happens after the initial rewrite.

**Comment by urinieto** [comment]
I'd support this.

**Comment by justinsalamon** [comment]
@urinieto @bmcfee 
Just having a look at this, it seems that most of the "old" parsers took an input folder, and an optional output folder (with -o), whilst the new SMC parser requires both. Also, the old parsers used ```logging``` to output some info (basically how long the conversion took).

Do we want to keep this kind of stuff consistent in the new parsers, or to each his own?

**Comment by urinieto** [comment]
I would say that logging is a bit of an overkill. Still, we should use
__future__ if we want to use print outs in order to make the parsers Python
2 and 3 compatible (as long we really want to print something out).

Regarding the input arguments, I don't care as long as we are consistent.

**Comment by bmcfee** [comment]
> Just having a look at this, it seems that most of the "old" parsers took an input folder, and an optional output folder (with -o), whilst the new SMC parser requires both.

Why should the output folder be optional?


> Also, the old parsers used logging to output some info (basically how long the conversion took).

I don't have strong opinions on this.  Logging mostly makes sense if we're implementing conversion as an API/library service, rather than a command-line program.



> Still, we should use
> __future__ if we want to use print outs in order to make the parsers Python
> 2 and 3 compatible

:+1:

**Comment by bmcfee** [comment]
Just as a side note, I noticed that the `datasets` directory is huge, and bloats the repository.  On a fresh checkout, I get the following:

```
[bmcfee@mariana:~/git]➔ du -hs jams/*
476M	jams/datasets
20K	jams/docs
8.5K	jams/examples
2.0K	jams/LICENSE
155K	jams/matjams
57K	jams/parsers
62K	jams/pyjams
3.0K	jams/README.md
13K	jams/schema
```

Maybe we should think about nuking this stuff sooner, rather than later?

**Comment by urinieto** [comment]
My suggestion: go for it.

**Comment by urinieto** [comment]
JKU dataset parser finished.

**Comment by bmcfee** [comment]
> JKU dataset parser finished.

@urinieto awesome!  feel like updating #26 and #16 while you're at it? :)

**Comment by bmcfee** [comment]
MEANWHILE

It sounds like nobody's objecting to subtree-splitting the data and parsers off into a separate repo (`jams-data` anyone?).

I'll do a little shuffling to make this work, then re-create this issue in the new repo.

**Comment by urinieto** [comment]
+1
