### ISSUE TITLE
Encapsulate exceptions?

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#33]
Should we provide encapsulated exceptions for jams?  For background, [read this](https://books.google.com/books?id=bTUFCAAAQBAJ&pg=PA185&lpg=PA185&dq=root+exception+class+python&source=bl&ots=G9c6YhxbGF&sig=CmGK3qnRTA6q_NNZBxklL57XYkc&hl=en&sa=X&ei=Sj5nVeL3PNSwyATEt4HwBg&ved=0CFEQ6AEwBw#v=onepage&q=root%20exception%20class%20python&f=false).

Currently, we throw a mixture of `TypeError`, `RuntimeError`, `ValueError`, and `jsonschema.ValidationError`, depending on the situation.  This makes it difficult to separate exceptions raised by JAMS from those raised in other packages.

Proposed solution:

Define a root exception class `JamsError` to encapsulate our own exceptions.  Then derive subclasses for the various types of exceptions we may encounter:

- `NamespaceError` Incorrect namespace for an annotation, eg, in the eval module
- `ValidationError` as in jsonschema
- other types, as needed?

**Comment by justinsalamon** [comment]
+1

**Comment by rabitt** [comment]
+1
In the space of namespace converters, something like `ConversionError` might be a nice one as well.

**Comment by bmcfee** [comment]
First cut is done and implemented throughout the unit tests.

I'm not married to any of the exception class names, so suggestions are welcome.  Currently we have:

- `JamsError` the root class.  All errors generated by JAMS subclass this.
- `ValidationError` exceptions arising from schema validation errors.
- `NamespaceError` exceptions arising from improper namespace usage.  For instance, calling `jams.eval.beat` on a chord annotation.  Or, in the future, trying to convert between incompatible namespaces.
- `ParameterError` exceptions arising from bad parameter values in methods and functions.  For example, calling `JAMS.add()` with `on_conflict='step on a lego'`.
- `MatchError` thrown when a meta-data merge fails.


Some possible improvements/changes:
- `ValidationError` -> `SchemaError`.  This will avoid colliding with `jsonschema.ValidationError` (which we trap and reinterpret where appropriate), and also be a bit more sensible for use in things like `JObject.__setattr__`, which throw exceptions when the schema is abused, but aren't really validation errors.
- I don't like `MatchError`.  Is there a more generic concept that we can use here?  Maybe we can just provide our own version of value or runtime error?

**Comment by justinsalamon** [comment]
> ```ValidationError``` -> ```SchemaError```. This will avoid colliding with ```jsonschema.ValidationError``` (which we trap and reinterpret where appropriate), and also be a bit more sensible for use in things like ```JObject.__setattr__```, which throw exceptions when the schema is abused, but aren't really validation errors.

+1

> I don't like ```MatchError```. Is there a more generic concept that we can use here? Maybe we can just provide our own version of value or runtime error?

```MetadataError```? ```MergeError```?

**Comment by bmcfee** [comment]
> MetadataError? MergeError?

Both of those are too specific, IMO.  You shouldn't have an entire class dedicated to one specific method's failure modes.

Perhaps the answer is to punt up to `JamsError` for this case, and then refine it later if we find similar cases throwing generic exceptions.
