### ISSUE TITLE
import_lab crashes

### ISSUE THREAD

**Issue by urinieto** [marl/jams#37]
`import_lab` crashes when it tries to parse something like:

```
0.432471655	New Point
0.873650793	New Point
1.358004535	1
1.822993197	2
2.287006802	3
2.740000000	4
```
(this example is copied from the Isophonics beat annotations for the track When I Get Home, from the album A Hard Day's Night, by The Beatles)

Pandas complains about not getting a float, but a string:
```
  File "./isophonics_parser.py", line 183, in <module>
    process(args.in_dir, args.out_dir)
  File "./isophonics_parser.py", line 128, in process
    jam=jam)
  File "/home/uri/Projects/jams/jams/util.py", line 81, in import_lab
    data.loc[:, 1] -= data[0]
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 182, in f
    result = method(self, other)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 524, in wrapper
    arr = na_op(lvalues, rvalues)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 475, in na_op
    result[mask] = op(x[mask], _values_from_object(y[mask]))
TypeError: unsupported operand type(s) for -: 'str' and 'float'
```

Should we default to 0 when a char/string is found in the last column?

**Comment by bmcfee** [comment]
The problem here is that it's an ill-formatted .lab file, and the logic for automatically inferring the number of columns fails.  Because the first row has three columns (when split by `\s+`), it thinks that the data is interval-keyed instead of event-keyed, and tries to subtract `0.432471655` from `New Point`.

Overriding the default separator here should fix it in this case:
```
>>> annotation = import_lab(..., sep='\t+')
```

**Comment by bmcfee** [comment]
As a side note: i'm not sure this is really a bug, but we could certainly do better at detecting failures and raising proper exceptions.

**Comment by urinieto** [comment]
Ok, I will add that to the Isophonics parsers. Thanks!

Wtr the bug: I guess it's an Isophonics "bug", but yes, I agree that it's
not really a problem of import_lab.

**Comment by bmcfee** [comment]
It's a problem insofar as import_lab failed to detect the number of columns properly.

A related question here is how to deal with the beat labels on those two spurious events.  I guess set them to `None` or `np.nan` is acceptable here?

**Comment by urinieto** [comment]
The namespace allows for nans, so I guess `np.nan` should be good. This
should go into import_lab.

**Comment by bmcfee** [comment]
I guess a separate point here: should we switch the default lab import separator to `\t+` (tabs) rather than `\s+` (whitespace)?

I seem to recall isophonics being inconsistent about this, but don't have a concrete example off the top of my head.

**Comment by urinieto** [comment]
I would say no, since most Isophonics lab files can be parsed only with
`\s+` (I only had to use `\t+` for a few beat lab files).

When I used `\t+` only, there were quite a few files that it couldn't parse
(more than the ones that `\s+` can't read).

**Comment by bmcfee** [comment]
Okay, so is there anything that actually needs changing in import_lab?  Or can we close this one out?

**Comment by urinieto** [comment]
I believe we can close this. Isophonics parser is up and it seems to be
working (using import_lab).
