### ISSUE TITLE
On Datatypes

### ISSUE THREAD

**Issue by ejhumphrey** [marl/jams#4]
The original JAMS proposal set out what we dubbed four atomic datatypes: Observation, Event, Range and TimeSeries. Somewhat unfortunately, at least in the sense consistent with chemistry, Event and Range are actually molecules composed of Observation atoms, so we were wrong in this regard. Not super crucial, but worth noting.

During development, we (or at least I) thought, "oh noes, we don't have a Table type!" This raised concerns about rows, headers, dimensionality, and all of these other concerns. 

Having conversations with folks at ISMIR about datatypes, it first seemed like we'd really only need two fundamental datatypes: an interval, for sparse phenomena, and a series, for dense data. In theory, everything could be stored as sparse points, but the main argument against it is that logical groups should be kept together, e.g. the frequency values of a pitch contour.

An effort to wrangle a modified schema, along with a validated JSON, can be found at c0dbcc69e:
- https://github.com/marl/jams/blob/ver2/schema/jams_schema_v2.json
- https://github.com/marl/jams/blob/ver2/examples/ejh_v2.json

However, spelling it out this way, it's interesting to consider that information can be sparse or dense in both over time and instantaneously:
- onset times of various drums are sparse in time and voicing
- pitch contours of multiple voices are dense in time, but sparsely voiced
- guitar chords are sparse in time, but should be stored as an array of six values
- instrument activations are dense in both time and voicing

For what it's worth, MIDI has solved these problems somewhat, by making everything a sparse (numerically coded) event. 

One challenge in building a schema around these ideas is whether to strictly assign tasks to types, probably through inheritance, or falling back to namespaces and letting something more powerful than a schema parse the data. It's an appealing idea to perform all validation in the schema, but it every conceivable structure would need to be defined explicitly.

**Comment by bmcfee** [comment]
I think pandas branch also resolves this issue.  Can we close?
