### ISSUE TITLE
jams_to_lab.py

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#43]
To be good citizens of the MIR world, we should provide a script that can crunch a jams file out to one or more .lab files.  (Of course, such a thing shouldn't be necessary, but it will be useful as an intermediate solution until the rest of the universe gets up to speed.)

I'm thinking the following:

```bash
$ jams_to_lab.py my_jam.jams prefix
```
will create a set of lab files of the form
```
prefix__namespace__index.lab
```
where `index` counts off how many annotations of type `namespace` there are.  For example, a SALAMI jams would give

```
prefix__segment_salami_function__0.lab
prefix__segment_salami_function__1.lab
prefix__segment_salami_upper__0.lab
prefix__segment_salami_upper__1.lab
prefix__segment_salami_lower__0.lab
prefix__segment_salami_lower__1.lab
```
each lab file would have JAMSy column headers, and comment headers including the file metadata and annotation metadata.  (Sandboxes will be omitted, I guess.)

Desired namespaces or annotators may be user-specified on the command line.

**Comment by urinieto** [comment]
+1

**Comment by justinsalamon** [comment]
future me says: death to lab files, don't do it!
past me says: i'm sure there will be people who will appreciate this, do it!
present me says: look, a butterfly!

**Comment by bmcfee** [comment]
Done, I think.

Someone give it a spin before I close this issue out?

**Comment by bmcfee** [comment]
One more thought: do we want to have namespace-specific output conversion, or just dump everything in a standard tabular format?

The specific use case I have in mind is tempo annotations, which have a very different .lab format from chords or beats.  If you want to use the exported lab files for evaluation, things will get messy.

OTOH, I like the simplicity of having a standardized output conversion layer.

What do people think?

**Comment by urinieto** [comment]
What is the tempo .lab format? And how hard would it be to just convert the
"generic" .lab produed by our script to the tempo .lab format? If the
process is not too convoluted, I would just leave this to the researcher.
Thus, we enforce a more "standardized" use of .lab files.

**Comment by bmcfee** [comment]
[Tempo format](http://www.music-ir.org/mirex/wiki/2015:Audio_Tempo_Estimation#Output_Data)

It's not complicated, and conversion could probably be hacked with judicious use of bash and pipes, but it would take a little effort.

Another issue with this: once we make one custom export converter, we'll probably have to make more.  I don't want to open that can of worms if we don't have to.

**Comment by urinieto** [comment]
I would just produce a standard lab and hope that other researchers, when
hacking these labs to adapt to crazy formats, realize that jams is better :)

**Comment by bmcfee** [comment]
Agreed.

Anything else we should cover on this one, or is it safe to close out?  (At least one other person ought to try running the converter script.. I hope.)

**Comment by urinieto** [comment]
We should close it. I tried it, and it seems to be working.
