### ISSUE TITLE
namespace corrections in general, and segment_tut

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#44]
It looks to me like `segment_tut`'s namespace has inherited some typos from the annotations that it's meant to describe.  I'm particularly talking about [this sort of thing](https://github.com/marl/jams/blob/develop/schema/namespaces/segment/tut.json#L28), which  looks like an obvious transcription error to me.

The question to you all: should we codify this kind of thing in the namespace definition?  Or instead, correct the namespace definition and use it to detect (and correct) errors in the source files?

(I vote for the latter, obviously.)

**Comment by urinieto** [comment]
I would also suggest the latter. But we should document all the errors to
be corrected. There's a bunch of them on SALAMI as well.

**Comment by bmcfee** [comment]
> But we should document all the errors to
> be corrected. There's a bunch of them on SALAMI as well.

This seems like it belongs in the `jams-data` documentation alongside the parse scripts.

**Comment by urinieto** [comment]
Agreed.
