### ISSUE TITLE
Publication of jams2

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#45]
@justinsalamon has repeatedly kicked around the idea of writing a paper to document the changes in jams over the last year.  I think this is probably a good idea, if only for publicity.

As for venues, the next obvious one is ismir2015 late breaking session (deadline: 2015-10-26).  This would be an extended abstract (2 pages), which clearly doesn't suffice to document all the restructuring.

It would be nice to have a longer document as well, either a tech report or an arxiv preprint, which the late breaking session abstract can refer back to for more details.  This means we'd have to crank out the paper by october, which should be plenty doable.

Who's in?

**Comment by justinsalamon** [comment]
this might come as a surprise, but... :+1: 

Do I hear a "pump up the jams" comeback?!

**Comment by rabitt** [comment]
+1 for doing this as an ismir late breaking paper. I think as @bmcfee said that the point of the paper is for publicity, and all it needs is a summary pointing back to a much longer more detailed document on the web somewhere. 

ALSO YES TO PUMP UP THE JAMS

**Comment by rabitt** [comment]
(btw, I think this goes without saying, but this is clearly a @bmcfee first author yaaa?)

**Comment by urinieto** [comment]
YES TO ALL :)))

**Comment by ejhumphrey** [comment]
+∞

**Comment by justinsalamon** [comment]
@bmcfee looks like it's all good to go chief. Latex / git / yada yada when you have time yada yada

**Comment by bmcfee** [comment]
Created https://github.com/marl/jams-paper for these guys.  Will probably not get around to populating it until august.

Closing out this issue now.
