### ISSUE TITLE
Validation caching

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#46]
It would be nice if we could somehow checksum and cache expensive operations, such as schema validation.

Once we validate a jams object, we shouldn't need to validate it again if it hasn't changed.

**Comment by urinieto** [comment]
Is there an easy way to do that using the @cache decorator?

**Comment by bmcfee** [comment]
> Is there an easy way to do that using the @cache decorator?

Yes, but we'd do better to use joblib.Memory directly.

It's still not a great solution though, since it would cache the entire object.  I'd rather checksum (or otherwise hash) the object first, and then cache that.

**Comment by bmcfee** [comment]
Having read through joblib.Memory docs, I'm not sure this idea is really feasible.  The big hurdle here is that the object being validated against the schema is split across multiple objects (eg, each annotation, sandbox, etc. is a separate object) that all get down-cast to dicts for the purposes of validation.  This means that caching at the top-level needs to maintain cache consistency of all of its sub-objects, which is going to require a lot of overhead.  I doubt it will buy us much.

I'll close this out, but if anyone wants to take it up again, feel free to re-open.
