### ISSUE TITLE
RFC: chord_roman and augmented triads

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#53]
[summarizing an offline conversation with @ejhumphrey and soliciting feedback from others, eg @jonforsyth @rabitt @justinsalamon ]

The `chord_roman` namespace is ported over from the [loose spec](http://theory.esm.rochester.edu/rock_corpus/harmonic_analyses.html#3.1C) defined in the rock corpus, but constrained to cover only the quality/categorical symbols used in the database.

An issue that popped up in writing documentation #23 is that the spec doesn't quite match the data.  Specifically, the spec says that augmented chords are marked with `'a'` (eg [superstition_tdc](http://theory.esm.rochester.edu/rock_corpus/harmonic_analyses/rs200_harmony/superstition_tdc.har)), but they seem to also be marked by `'+'` (eg [fast_car_tdc](http://theory.esm.rochester.edu/rock_corpus/harmonic_analyses/rs200_harmony/fast_car_tdc.har)).

Two questions:

1. Should we eliminate one of these formats to reduce confusion?  If so, which one?  The resulting trc parser will need to handle translation, but this doesn't seem like too big of a deal. (Note: the original spec allowed for arbitrary strings, which I really would like to avoid.)
2. Or should we keep both, allowing for redundancy/ambiguity, but keeping the translation simple?

My personal vote is for adhering to the intended spec, dropping `'+'` and keeping `'a'`, but I could be persuaded either way.

**Comment by jonforsyth** [comment]
My vote would be to drop 'a' and keep '+', if only because it's much more commonly used in regular music notation (chord charts, etc).

**Comment by bmcfee** [comment]
> My vote would be to drop 'a' and keep '+'


I'm fine with that also, since there isn't really a prevalence for one or the other exposed in the trc data.  (Also, it's consistent with [wikipedia](https://en.wikipedia.org/wiki/Roman_numeral_analysis#Common_practice_numerals), for whatever that's worth.)

Any objections?

**Comment by justinsalamon** [comment]
> My vote would be to drop 'a' and keep '+', if only because it's much more commonly used in regular music notation (chord charts, etc).

+1
Or keep both (I have no preference in that respect), but if we drop one I'd definitely keep the "+" over the "a" (e.g. in the real book I've also seen "+5" and "aug" in addition to the more common "+", but never just "a" I don't think)

**Comment by bmcfee** [comment]
Ok, it sounds like there's a majority leaning toward `'+'` over `'a'` if we decide to drop one.  (@ejhumphrey had expressed a preference for 'a' offline).

Second question: do we actually drop one, or keep both?

* Arguments for dropping:
  * there's one way to encode aug
  * everything is minimal
* Arguments for keeping:
  * keeping both doesn't present a real technical challenge, just a minor inconvenience
  * compatibility with trc

**Comment by ejhumphrey** [comment]
to clarify, my preference is "aug > + > a"

**Comment by bmcfee** [comment]
> to clarify, my preference is "aug > + > a"

Aha, i didn't catch that before. Thanks.

'aug' doesn't fit the rest of the scheme here (single-character patterns), so I'd prefer to stick to +.

**Comment by bmcfee** [comment]
> Second question: do we actually drop one, or keep both?

I suppose we have enough (implicit) votes to go ahead with dropping `'a'` in favor of `'+'`.

If, for some reason down the line, we want to support raw trc files, we can always add a less restrictive namespace `chord_rock_corpus` (or somesuch).

Closing this one out now.
