### ISSUE TITLE
Namespace for numeric values (eg regression targets)

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#58]
Just like the mood_thayer namespace, but for data of arbitrary dimension.

The use-cases here are things like [latent factor prediction](http://papers.nips.cc/paper/5004-deep-content-based-music-recommendation).

**Comment by bmcfee** [comment]
One complicating factor here: it may not be possible to enforce (at the schema level) that all observations have the same length. For example, I don't see a way to prohibit the following:

time | duration | confidence | value
------|------------|-----------------|--------
    0 |          20 |            null | [0]
      0 |          20 |            null | [0, 1]
      0 |          20 |            null | [0, 1, 2]

This doesn't bother me too much, but it would be nice to not have to worry about it.

**Comment by bmcfee** [comment]
Do we still need/want this if we implement #62 ?

**Comment by rabitt** [comment]
:+1:

**Comment by bmcfee** [comment]
Implemented by #64
