### ISSUE TITLE
Schema error when saving .jams file from jams.util.import_lab()

### ISSUE THREAD

**Issue by wangsix** [marl/jams#59]
I was trying to save SALAMI .lab files into .jams files but encountered this error. 
The code was like this 
```
for lab in labs:
    jam, annotation = jams.util.import_lab('segment_open',lab_path+lab)
    jam.save(dump_path+'SALAMI_'+lab[:-4]+'.jams')
```

I tried 'segment_salami_function' and 'segment_salami_upper'. Both return the same error. Please let me know if I misunderstood the usage of jams or any pointers. Thanks!! 

Error messages:
>---------------------------------------------------------------------------
SchemaError                               Traceback (most recent call last)
<ipython-input-4-522ab24b0d10> in <module>()
      1 for lab in labs:
      2     jam, annotation = jams.util.import_lab('segment_open',lab_path+lab)
----> 3     jam.save(dump_path+'SALAMI_'+lab[:-4]+'.jams')

>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jams-0.2.0-py2.7.egg/jams/core.pyc in save(self, path_or_file, strict, fmt)
   1168         """
   1169 
-> 1170         self.validate(strict=strict)
   1171 
   1172         with _open(path_or_file, mode='w', fmt=fmt) as fdesc:

>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jams-0.2.0-py2.7.egg/jams/core.pyc in validate(self, strict)
   1198 
   1199         '''
-> 1200         valid = super(JAMS, self).validate(strict=strict)
   1201 
   1202         for ann in self.annotations:

>/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jams-0.2.0-py2.7.egg/jams/core.pyc in validate(self, strict)
    476         except jsonschema.ValidationError as invalid:
    477             if strict:
--> 478                 raise SchemaError(str(invalid))
    479             else:
    480                 warnings.warn(str(invalid))

>SchemaError: None is not of type u'number'

>Failed validating u'type' in schema[u'properties'][u'file_metadata'][u'properties'][u'duration']:
    {u'minimum': 0.0, u'type': u'number'}

>On instance[u'file_metadata'][u'duration']:
    None

**Comment by bmcfee** [comment]
```
On instance[u'file_metadata'][u'duration']:
None
```

That's your problem: track duration is a required field in JAMS objects, and you're not setting it.  This is briefly covered in the examples section of the documentation, eg [here](http://pythonhosted.org/jams/examples.html#example-beat-py) and [here](http://pythonhosted.org/jams/examples.html#example-chord-import-py).

There are a few reasons why this field is required:

* it's information that should always be available at annotation-time, and it's useful to keep around.
* knowing the duration can help with the conversion of event boundaries (generally bad) to intervals (generally good); this is particularly useful in salami land.
* disambiguation.  Short of storing an audio fingerprint (which you can also do in the sandbox), this provides a quick (but perhaps coarse) way to verify that you have the right version of the audio file to match the annotation.

If you don't have the audio on-hand, you can hack the duration from an annotation by following the chord-import example in the documentation (linked above).

**Comment by wangsix** [comment]
Thank you! I followed [this example](http://pythonhosted.org/jams/examples.html#example-chord-import-py) and fixed my code.
