### ISSUE TITLE
Python API doesn't validate intervals when created / written.

### ISSUE THREAD

**Issue by ejhumphrey** [marl/jams#6]
Caught a bug (I think?) in the Isophonics import, where a start time > end time:

```
          {
          "start": {
            "value": 188.854
          }, 
          "end": {
            "value": 188.827
          }, 
          "label": {
            "value": "silence"
          }
```

https://github.com/marl/jams/blob/master/datasets/Isophonics/The%20Beatles/10CD1_-_The_Beatles/CD1_-_04_-_Ob-La-Di%2C_Ob-La-Da.jams#L4126

Not really sure how to fix / hack this. The duration of the file I've got is 188.839, which doesn't match the annotation, nor is it smaller than this final interval.

**Comment by bmcfee** [comment]
Pandas branch has optional strict dumping, and schema validates intervals (durations), which resolves the initial issue.

Shall we close this one?

**Comment by CyxouD** [comment]
TUT Beatles annotations link is broken, so for those searching here it is in @urinieto's repository https://github.com/urinieto/msaf-data/tree/master/BeatlesTUT/references
