### ISSUE TITLE
Namespace: unstructured blob

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#62]
![blob](https://upload.wikimedia.org/wikipedia/en/thumb/0/07/Blobm.PNG/250px-Blobm.PNG)

Sometimes we might end up with tasks that are too idiosyncratic to schematize, but that we nonetheless want to collect in JAMS objects.

We can define a blanket namespace `blob` for this situation, which allows for unstructured (and unvalidated) data to be stored as jams annotations.  This is analogous to `tag_open`, but without (string) type safety on `value`.

**Comment by urinieto** [comment]
This sounds like a great idea.
