### ISSUE TITLE
Search in sandbox

### ISSUE THREAD

**Issue by urinieto** [marl/jams#70]
I am trying to search an annotation that has a specific value in its sandbox, but I'm not sure how to use the `search` function.

If the sandbox field looks like this:

```"sandbox": {
    "test": "titan"
}```

How should I call the `search` function in order to get this annotation?

Thanks!

**Comment by bmcfee** [comment]
https://gist.github.com/2513087f4f350f52e43a shows an example of how to do this.

The complicating factor here is that searching on nested objects requires some strange syntax, ie, the `.` operator.  This screws up python's keyword-argument parsing if you do it directly, say `jam.search(Sandbox.foo='bar')`, but if you use the ** magic, everything works as expected.

**Comment by bmcfee** [comment]
Follow-up note: you could also search on the bare field name directly:
```python
annotatoins = jam.search(test='titan')
```
and that would also work.  If you have unique field names that don't collide with anything else in the `Annotation` object hierarchy (eg, `AnnotationMetadata`,  `Curator`, or `JamsFrame`), this might be preferable.

**Comment by urinieto** [comment]
Awesome, it works. It's confusing, since "sandbox" in the JAMS file itself does not have an upper case 'S', but I guess it's looking for the actual object, which is capitalized.

Regardless, thanks titan!

**Comment by urinieto** [comment]
Mmhh I have another question: how do I make joint queries with this syntax? Let's say I want to find the same sandbox test _and_ `namespace="segment_salami_upper"`. What would be the best way to do it?

Thanks again!

**Comment by bmcfee** [comment]
> Awesome, it works. It's confusing, since "sandbox" in the JAMS file itself does not have an upper case 'S', but I guess it's looking for the actual object, which is capitalized.

Right, because it's searching over the type, not the instance variable itself.  This may seem weird, but it's the only way to be consistent when you can have multiple objects of the same type, as is the case with an array of annotations.  Using the class name anonymizes the object.


> Mmhh I have another question: how do I make joint queries with this syntax? Let's say I want to find the same sandbox test and namespace="segment_salami_upper". What would be the best way to do it?

By 'joint' you mean 'conjunctive'.  JAMS queries are disjunctive by default, so you can do OR queries directly:
```python
results = jam.search(**{'namespace': 'foo', 'Sandbox.test': 'titan'})
```

If you want a conjunction (AND) query, you can post-process the results array.  It's an AnnotationArray type, and not a vanilla list, so the following would work:
```python
results = jam.search(namespace='segment_salami_upper').search(**{'Annotation.Sandbox.test': 'titan'})
```
(of course, you can swap the order of these searches too.)

I agree that it's clunky, but we had to make an executive decision about which mode to support directly, and this way of arranging it made for a relatively clean implementation.

**Comment by urinieto** [comment]
Well, despite its "clunkiness", I still think that it is awesome to have this functionally.

Thanks!

**Comment by urinieto** [comment]
Another related question (sorry titan). All of this works as long as the type of the value you're searching is a `string`. But when the value of is an `int` (e.g., `"sandbox": {"test": 1}`), I get the following error when doing `jam.search(**{"Sandbox.test"}: 1})`:

```
Traceback (most recent call last):
  File "./run_msaf.py", line 135, in <module>
    main()
  File "./run_msaf.py", line 116, in main
    res = func.process(args.in_path, **params)
  File "/Users/uri/NYU/Dissertation/msaf_github/msaf/run.py", line 357, in process
    boundaries_id, labels_id, **config)
  File "/Users/uri/NYU/Dissertation/msaf_github/msaf/input_output.py", line 400, in save_estimations
    curr_ann = find_estimation(jam, boundaries_id, labels_id, params)
  File "/Users/uri/NYU/Dissertation/msaf_github/msaf/input_output.py", line 336, in find_estimation
    ann = ann.search(**{"Sandbox.L_peaks": 64})
  File "/Users/uri/NYU/Dissertation/jams/jams/core.py", line 1022, in search
    if annotation.search(**kwargs):
  File "/Users/uri/NYU/Dissertation/jams/jams/core.py", line 447, in search
    match |= obj.search(**r_query)
  File "/Users/uri/NYU/Dissertation/jams/jams/core.py", line 440, in search
    match |= match_query(getattr(self, key), r_query[key])
  File "/Users/uri/NYU/Dissertation/jams/jams/core.py", line 1285, in match_query
    raise ParameterError('Invalid query type: {}'.format(type(query)))
jams.exceptions.ParameterError: Invalid query type: <type 'int'>
```

If I change the `**{"Sandbox.L_peaks": 64}` to `**{"Sandbox.L_peaks": "64"}`, I get the following error, since the variable in jams `L_peaks` is an `int`:

```
Traceback (most recent call last):
  File "./run_msaf.py", line 135, in <module>
    main()
  File "./run_msaf.py", line 116, in main
    res = func.process(args.in_path, **params)
  File "/Users/uri/NYU/Dissertation/msaf_github/msaf/run.py", line 357, in process
    boundaries_id, labels_id, **config)
  File "/Users/uri/NYU/Dissertation/msaf_github/msaf/input_output.py", line 400, in save_estimations
    curr_ann = find_estimation(jam, boundaries_id, labels_id, params)
  File "/Users/uri/NYU/Dissertation/msaf_github/msaf/input_output.py", line 336, in find_estimation
    ann = ann.search(**{"Sandbox.L_peaks": "64"})
  File "/Users/uri/NYU/Dissertation/jams/jams/core.py", line 1022, in search
    if annotation.search(**kwargs):
  File "/Users/uri/NYU/Dissertation/jams/jams/core.py", line 447, in search
    match |= obj.search(**r_query)
  File "/Users/uri/NYU/Dissertation/jams/jams/core.py", line 440, in search
    match |= match_query(getattr(self, key), r_query[key])
  File "/Users/uri/NYU/Dissertation/jams/jams/core.py", line 1283, in match_query
    return re.match(query, string) is not None
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```

Any idea on how to do this? Thanks!

**Comment by bmcfee** [comment]
> Another related question (sorry titan). All of this works as long as the type of the value you're searching is a string.

Query targets are either a regular expression (string) or a lambda function.  If you want to match on ints, then do something like:

```python
jam.search(**{"Sandbox.test"}: lambda x: x == 1})
```

I suppose we could extend the search logic to use `==` by default on non-callables.

**Comment by urinieto** [comment]
Awesome, thanks!
