### ISSUE TITLE
Jams 0.2 announcement

### ISSUE THREAD

**Issue by justinsalamon** [marl/jams#74]
Is it worth sending out an announcement about v0.2.0 to the ismir mailing list (and any other relevant lists) with links to the LBD abstract (once ready) & tech report as well as inviting people to come check the LBD during ISMIR 2015?

**Comment by bmcfee** [comment]
I punted a bunch of non-essential issues up to 0.2.2.  Maybe we should hold off for 0.2.1, which really only depends on implementing local namespaces #55 ?  I was planning to hack that out tomorrow anyway.

**Comment by justinsalamon** [comment]
sounds sensible. I think the only "deadline" to consider is that it would be nice to get this out before ismir, so that you can pimp it out during the conference.

**Comment by urinieto** [comment]
I vote +1 for the announcement (once it's ready).
