### ISSUE TITLE
[pyjams] discussion: data frame layer?

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#8]
I've been trying to work with pyjams, and keep running into the same stumbling blocks that we've discussed offline.  To summarize:

* It's a little too cumbersome to get at the data programmatically.  For instance, to interface with mir_eval currently requires a considerable amount of slicing, dicing, and repacking.
* Modifying a jams (pyjams) object in memory is similarly difficult.  What if I trim a track's audio file and want to modify all time boundaries to match?  There's no simple way to do this right now.

After digging around a bit, I think it makes a lot of sense to use [pandas](http://pandas.pydata.org/) DataFrames as an in-memory representation for several observation types.  Rather than go into detail of how exactly this might look, I mocked up a notebook illustrating the main concepts with a chord annotation example [here](http://nbviewer.ipython.org/gist/bmcfee/63c8d0b68e7b98bcd1ee).

The key features are:

* Hierarchical indexing, so that a field like "start" can have both "value" and "confidence" measurements associated with it
* Mixed data type storage
* All the pandas goodies (support for querying/slicing, missing data, etc)
* Distinguishing time-typed and categorical data from other numeric values. (This bit would have to be enforced by the schema, but I think that's probably okay.)
* Easy to slice and reinterpret a frame as a numpy array, allowing easy interaction with mir_eval (among others).

The way I see this playing out is that the json objects would stay pretty much the same on disk (modulo any schema changes we cook up for convenience).  However, when serializing/deserializing, certain arrays get translated into pandas dataframes, which is the primary backing store in memory.

For example, a chord annotation record `my_jams.chord[0].data`, rather than being a list of `Range` objects, can instead be a single DataFrame which encapsulates all measurements asociated with the annotation.  The jams object still retains hierarchy and multi-annotation collections, but each annotation becomes a single object, rather than a list of more atomic types.

If people are on board with this idea, I'd like to propose adopting a couple of conventions to make life easier:

- Any measurement value corresponding to time (eg, event or interval boundary markers) should use the `timedelta[ns]` data type, rather than a float.  Aside from making time values easy to find, pandas also provides some nice functionality for working with time series data.
- Anything that could be interpreted as a "label" (eg, chord labels, segment ids, pitch class, instrument, etc) should use dtype 'category' rather than 'str' or 'object'.
- If a value is not measured, use `nan` rather than hallucinating data or leaving the record empty. (I'm looking at you, confidence values.)

I realize that this adds yet another dependency and source of complexity to something that's already pretty monstrous, but I think it'll be worth it in the long run.  Of course, this is all intended as a long-winded question/request for comments, so feel free to shoot it all down.

**Comment by urinieto** [comment]
Just wanted to say that I finally reviewed this question with its [multiple] (http://nbviewer.ipython.org/gist/bmcfee/fe3eedf42262ced19e2d) [associated](http://nbviewer.ipython.org/gist/bmcfee/8ef20481b90cb540b1fd) [note] (http://nbviewer.ipython.org/gist/bmcfee/d638b8634becb7a62c0d) [books] (http://nbviewer.ipython.org/gist/bmcfee/63c8d0b68e7b98bcd1ee) and I should say I fully support the usage of pandas in jams.

I would also vote (3).

Moreover, the **JamsFrame** makes a lot of sense and seems to make things even clearer.

Since I already use pandas in [msaf] (https://github.com/urinieto/msaf), I am really looking forward to integrating this new jams version with msaf, so that I can provide some feedback when using this version _in the wild_.

**Comment by bmcfee** [comment]
Over the weekend, I wrote an import script for the [SMC beat tracking dataset](http://smc.inescporto.pt/research/data-2/).

Here's an [ipynb](http://nbviewer.ipython.org/gist/bmcfee/c3c0f560789b2c1886e1) showing how this all works out, now that the dust has settled.  I'm pretty happy with it.

**Comment by rabitt** [comment]
This is great.
