### ISSUE TITLE
namespace: lyrics_bow

### ISSUE THREAD

**Issue by bmcfee** [marl/jams#81]
We should have a way to represent bag-of-words representations of lyrics (over a time interval).

This could be encoded as tuples: `(string, count)`, or as a dictionary: `{string: count}`.

Alternately, we could make it a generic n-gram counter, in which case you'd have `([str1, str2, ... strn], count)`.

What do folks think?

**Comment by bmcfee** [comment]
[paging @mattmcvicar]

After some pondering on this, here are some thoughts:

- Any observation will have to be a collection of some kind, otherwise we'd have one observation per term.
- A dict would be great, but it wouldn't allow ngrams.  In python, you could do this by having tuple keys, but you can't have array keys in js/json.
- If the observation is a list of tuples ``[(term, count)]`` where ``term`` can be a string or a list, it's fairly trivial to make a sane python dictionary out of that:  ``dict([ (tuple(t), c) for (t,c) in obs])``
- Is it worth trying to support both words and ngrams in one namespace? Or have separate namespaces for each? (I lean toward one namespace, but could be persuaded.)

**Comment by bmcfee** [comment]
Additional comments:

- The `dict` mapping described above can dump directly into `sklearn`'s `DictVectorizer` object and do the right thing, which is nice.
- Counts should be non-negative. Non-integer values are okay though, since we may have normalized frequency counts rather than raw numbers.

**Comment by mattmcvicar** [comment]
Hi all, sorry the delay here.

My feeling is that whilst extending to n-grams is nice, it's more of a
modelling problem than a data storage one. As long as one is able to create
n-grams from a collection of 1-grams, I would prefer keeping it simple. I
prefer {word : count} as then it's easy to retrieve individual words in the
case of a large vocab.


On Mon, Feb 1, 2016 at 5:24 PM, Brian McFee <notifications@github.com>
wrote:

> Additional comments:
>
>    - The dict mapping described above can dump directly into sklearn's
>    DictVectorizer object and do the right thing, which is nice.
>    - Counts should be non-negative. Non-integer values are okay though,
>    since we may have normalized frequency counts rather than raw numbers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marl/jams/issues/81#issuecomment-178080390>.
>



-- 
Matt McVicar
Research Associate in Data Science
Intelligent Systems Laboratory, University of Bristol
contact: mattjamesmcvicar@gmail.com
blog/website: www.mattmcvicar.com

**Comment by bmcfee** [comment]
> My feeling is that whilst extending to n-grams is nice, it's more of a
> modelling problem than a data storage one.

I disagree: you can't convert 1-grams to n-grams without sequence information, which has to be stored somewhere.

This namespace provides for both use-cases, so if you want only 1-grams, that's totally fine.  It's also relatively easy to filter out n-grams by checking for non-string types.

(Of course, we could also have a simple namespace for 1-grams, if people really want that.  I'd rather not have duplicated effort though.)

**Comment by mattmcvicar** [comment]
On Tue, Feb 9, 2016 at 6:57 PM, Brian McFee <notifications@github.com>
wrote:

> My feeling is that whilst extending to n-grams is nice, it's more of a
> modelling problem than a data storage one.
>
> I disagree: you can't convert 1-grams to n-grams without sequence
> information, which has to be stored somewhere.
>

​For sure - but I guess I'm struggling to imagine situations where one
would have n-grams for n > 1 but not access to the 1-grams themselves. I
guess if using something like the musixmatch data, which only has a BOW for
the entire song, so you'd have a single timestamp over the entire song and
the corresponding BOW?

> This namespace provides for both use-cases, so if you want only 1-grams,
> that's totally fine. It's also relatively easy to filter out n-grams by
> checking for non-string types.
>
> (Of course, we could also have a simple namespace for 1-grams, if people
> really want that. I'd rather not have duplicated effort though.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marl/jams/issues/81#issuecomment-182003965>.
>



-- 
Matt McVicar
Research Associate in Data Science
Intelligent Systems Laboratory, University of Bristol
contact: mattjamesmcvicar@gmail.com
blog/website: www.mattmcvicar.com

**Comment by bmcfee** [comment]
> ​For sure - but I guess I'm struggling to imagine situations where one
> would have n-grams for n > 1 but not access to the 1-grams themselves

Ah, the whole point here is to have both in the same place.

**Comment by bmcfee** [comment]
BTW, the [documentation](https://github.com/marl/jams/blob/namespace_lyrics_bow/docs/namespaces/lyrics.rst#lyrics_bow) illustrates an example of what this would look like.

**Comment by mattmcvicar** [comment]
I had a look at the example and I don't think it's the most elegant
solution.

The idea is to hold only BOW format right? To me, a BOW format is simply a
count of words, with no "n". If this is what we're aiming for, I would
simply do the following:

Input text "row row row your boat"

time
0.000

duration
30.00

value
{'row' : 3, 'your' : 1, 'boat' : 1}

If instead, the idea is to hold more general n-grams, I would go for:

value
{1 : {('row',) : 3, ('your',) : 1, ('boat',) : 1},
 2 : {('row', 'row') : 1, ('row', 'your') : 1, ('boat', 'your') : 1},
 3 : {('row', 'row', 'row') : 1, ('row', 'row', 'your') : 1, ('boat',
'row', 'your') : 1}
etc for 4, 5
}

This way its trivial to access all the ngram data via value[n]. It's also
(relatively) easy to pick out all n-grams which contain a particular word:

n = 2
y = [{gram : count} for gram, count in value[n].items() if 'row' in gram]
[{('row', 'your'): 1}, {('row', 'row'): 1}]

One caveat is redundancy in the string tuples. Notice above that I sorted
the strings when used as keys. The alternative would be to include all
possible permutations, for example:

 2 : {('row', 'row') : 1, ('row', 'your') : 1, ('your', 'row') : 1,
('boat', 'your') : 1, ('your', 'boat') : 1}

but obviously as n increases this becomes unwieldy.


On Tue, Feb 9, 2016 at 11:34 PM, Brian McFee <notifications@github.com>
wrote:

> BTW, the documentation
> <https://github.com/marl/jams/blob/namespace_lyrics_bow/docs/namespaces/lyrics.rst#lyrics_bow>
> illustrates an example of what this would look like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marl/jams/issues/81#issuecomment-182133725>.
>



-- 
Matt McVicar
Research Associate in Data Science
Intelligent Systems Laboratory, University of Bristol
contact: mattjamesmcvicar@gmail.com
blog/website: www.mattmcvicar.com

**Comment by bmcfee** [comment]
> The idea is to hold only BOW format right?

No, the idea was to hold single-term or n-gram counts.  Like I said before, if we want a second, simplified version for vanilla bow, we can do that too.


> This way its trivial to access all the ngram data via value[n].

I wasn't thinking of that as a common use-case.  Maybe I'm wrong?

It's worth noting that you can't enforce constant (but arbitrary) array-lengths in schema, so validating data in the ``{n: {gram: count} }`` format would either need custom-logic (which I'm loathe to do), or follow the ostrich algorithm.

Anyway, I totally agree that mixing types (string and list) is pretty gruesome here.  The only real benefit to doing it is that the data can dump directly into `DictVectorizer` with no additional unpacking.

Maybe it would help to come up with a plausible application and optimize for that, rather than hypothetical post-processing.  Any takers?

> The alternative would be to include all
> possible permutations, for example:

You would have to do this to disambiguate ``(row, your)`` from ``(your, row)``, which are distinct n-grams.  It could be made more efficient by hashing tokens, but then we'd lose human readability.  (Besings, `jamz` should figure out the redundancy at compression-time anyway.)

**Comment by mattmcvicar** [comment]
On Wed, Feb 10, 2016 at 12:47 PM, Brian McFee <notifications@github.com>
wrote:

> The idea is to hold only BOW format right?
>
> No, the idea was to hold single-term or n-gram counts. Like I said before,
> if we want a second, simplified version for vanilla bow, we can do that too.
>

​Now I don't understand your example at all. If you want n-gram counts
shouldn't your example also include counts for ('row', 'your'), ('your',
'boat') as well, as well as the 3 3-grams, 2 4-grams and the complete
5-gram? Or did you just skip them for brevity?
​


> This way its trivial to access all the ngram data via value[n].
>
> I wasn't thinking of that as a common use-case. Maybe I'm wrong?
>

​The most common use case I can see for these kinds of data are building
language models of some kind. Normally one would specify n a priori here.
It's also the top-level organisation of the ARPA format:

http://cmusphinx.sourceforge.net/wiki/sphinx4:standardgrammarformats

Basically, the choice is to make either the grams or the ns the most easily
accessed. I can see cases where both would be useful, but having n at the
top makes the most logical sense to me.


> It's worth noting that you can't enforce constant (but arbitrary)
> array-lengths in schema, so validating data in the {n: {gram: count} }
> format would either need custom-logic (which I'm loathe to do), or follow
> the ostrich algorithm.
>
>
​Ah I didn't realise that.​

Anyway, I totally agree that mixing types (string and list) is pretty
> gruesome here. The only real benefit to doing it is that the data can dump
> directly into DictVectorizer with no additional unpacking.
>
> Maybe it would help to come up with a plausible application and optimize
> for that, rather than hypothetical post-processing. Any takers?
>

Personally I see the BOW format itself as a bit contrived. A BOW
representation almost by definition has no timing information, so I'm
struggling to think of when it would be useful.


> ​
> The alternative would be to include all
> possible permutations, for example:
>
> You would have to do this to disambiguate (row, your) from (your, row),
> which are distinct n-grams. It could be made more efficient by hashing
> tokens, but then we'd lose human readability. (Besings, jamz should
> figure out the redundancy at compression-time anyway.)
>

​Sure, you're right. ​



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marl/jams/issues/81#issuecomment-182357351>.
>



-- 
Matt McVicar
Research Associate in Data Science
Intelligent Systems Laboratory, University of Bristol
contact: mattjamesmcvicar@gmail.com
blog/website: www.mattmcvicar.com

**Comment by bmcfee** [comment]
> Or did you just skip them for brevity?

yeah, my bad; laziness wins out.

> ​The most common use case I can see for these kinds of data are building
> language models of some kind

Yup, though I don't think people do this so much in music.  More often, I see lyrics used as an input feature to some other prediction task (similarity, classification, playlisting, etc).

> It's also the top-level organisation of the ARPA format:

Hey, a pre-existing standard to mimic! That's something.



> A BOW
> representation almost by definition has no timing information, so I'm
> struggling to think of when it would be useful.

Sure; I imagine most applications of this would use track-level annotations and the timing wouldn't be informative.  It's there because A) it's jams spec, and B) it can't hurt.  (It might also be useful for annotating which parts of a track have vocals/lyrics, but this may be better covered by the Annotation's time/value fields.)

**Comment by mattmcvicar** [comment]
On Wednesday, February 10, 2016, Brian McFee <notifications@github.com>
wrote:

> Or did you just skip them for brevity?
>
> yeah, my bad; laziness wins out.
>

No worries, just confused me a little. BTW, the example for vanilla lyrics
is a little in standard as well. It's usually reserved for a single word. I
​ ​
understand the additional flexibility offered
​by having multiple words on the same line (sometimes only phrase-level
timing will be available), but just thought I'd check so that you know it's
non-standard.​


> ​The most common use case I can see for these kinds of data are building
> language models of some kind
>
> Yup, though I don't think people do this so much in music. More often, I
> see lyrics used as an input feature to some other prediction task
> (similarity, classification, playlisting, etc).
>

​Sure.
​


> It's also the top-level organisation of the ARPA format:
>
> Hey, a pre-existing standard to mimic! That's something.
>

​Well, it's something! Although the files are always compressed into binary
anyway, so the formatting is only really useful for incredibly small
models.​


> A BOW
> representation almost by definition has no timing information, so I'm
> struggling to think of when it would be useful.
>
> Sure; I imagine most applications of this would use track-level
> annotations and the timing wouldn't be informative. It's there because A)
> it's jams spec, and B) it can't hurt. (It might also be useful for
> annotating which parts of a track have vocals/lyrics, but this may be
> better covered by the Annotation's time/value fields.)
>

​Agreed. So, maybe something like this would work?

{
 1 : [(('row',), 3), (('your',), 1), (('boat',), 1)],
 2 : [(('row', 'row'), 2), (('row', 'your'), 1), (('your', 'boat'), 1)],
 3 : [(('row', 'row', 'row'), 1), (('row', 'row', 'your'), 1), (('row',
'your', 'boat'), 1)],
 4 : [(('row', 'row', 'row', 'your'), 1), (('row', 'row', 'your', 'boat')
,1)],
 5 : [(('row', 'row', 'row', 'your', 'boat'), 1)]
}

ie a dict with keys equal to n-gram, then an unordered list of grams, which
are themselves a 2-ple of grams and counts.

**Comment by bmcfee** [comment]
> No worries, just confused me a little. BTW, the example for vanilla lyrics
> is a little in standard as well. It's usually reserved for a single word.

You can use it that way, but since A) strings are arbitrary and you can use it that way, and B) there's often uncertainty at the word-level, this didn't matter too much.
